//! OpenAPI/Swagger documentation
//!
//! Defines the `OpenAPI` spec for `SyncTV`'s HTTP REST API.
//! Since proto types are auto-generated by prost, we define manual schemas here.

use utoipa::openapi::security::{HttpAuthScheme, HttpBuilder, SecurityScheme};
use utoipa::{Modify, OpenApi, ToSchema};

// ============== Schema types for OpenAPI documentation ==============
// These mirror the proto-generated types but with ToSchema derives.

#[derive(ToSchema)]
#[schema(example = json!({"id": "abc123", "username": "alice", "email": "alice@example.com", "role": "user", "status": "active", "created_at": 1700000000, "email_verified": true}))]
pub struct UserSchema {
    pub id: String,
    pub username: String,
    pub email: String,
    pub role: String,
    pub status: String,
    pub created_at: i64,
    pub email_verified: bool,
}

#[derive(ToSchema)]
#[schema(example = json!({"id": "room_abc", "name": "Movie Night", "description": "Watch movies together every Friday", "created_by": "user123", "status": "active", "member_count": 5, "created_at": 1700000000, "updated_at": 1700000000}))]
pub struct RoomSchema {
    pub id: String,
    pub name: String,
    pub description: String,
    pub created_by: String,
    pub status: String,
    pub member_count: i32,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(ToSchema)]
#[schema(example = json!({"id": "media_abc", "room_id": "room_abc", "url": "https://example.com/video.mp4", "provider": "direct", "title": "video.mp4", "position": 0, "added_at": 1700000000, "added_by": "user123"}))]
pub struct MediaSchema {
    pub id: String,
    pub room_id: String,
    pub url: String,
    pub provider: String,
    pub title: String,
    pub position: i32,
    pub added_at: i64,
    pub added_by: String,
}

#[derive(ToSchema)]
#[schema(example = json!({"room_id": "room_abc", "playing_media_id": "media_abc", "position": 42.5, "speed": 1.0, "is_playing": true, "updated_at": 1700000000, "version": 1}))]
pub struct PlaybackStateSchema {
    pub room_id: String,
    pub playing_media_id: String,
    pub position: f64,
    pub speed: f64,
    pub is_playing: bool,
    pub updated_at: i64,
    pub version: i32,
}

#[derive(ToSchema)]
#[schema(example = json!({"room_id": "room_abc", "user_id": "user123", "username": "alice", "permissions": 7, "joined_at": 1700000000, "is_online": true}))]
pub struct RoomMemberSchema {
    pub room_id: String,
    pub user_id: String,
    pub username: String,
    pub permissions: i64,
    pub joined_at: i64,
    pub is_online: bool,
}

// --- Auth schemas ---

#[derive(ToSchema)]
#[schema(example = json!({"username": "alice", "password": "secret123", "email": "alice@example.com"}))]
pub struct RegisterRequestSchema {
    pub username: String,
    pub password: String,
    pub email: String,
}

#[derive(ToSchema)]
pub struct RegisterResponseSchema {
    pub user: Option<UserSchema>,
    pub access_token: String,
    pub refresh_token: String,
}

#[derive(ToSchema)]
#[schema(example = json!({"username": "alice", "password": "secret123"}))]
pub struct LoginRequestSchema {
    pub username: String,
    pub password: String,
}

#[derive(ToSchema)]
pub struct LoginResponseSchema {
    pub user: Option<UserSchema>,
    pub access_token: String,
    pub refresh_token: String,
}

#[derive(ToSchema)]
#[schema(example = json!({"refresh_token": "eyJ..."}))]
pub struct RefreshTokenRequestSchema {
    pub refresh_token: String,
}

#[derive(ToSchema)]
pub struct RefreshTokenResponseSchema {
    pub access_token: String,
    pub refresh_token: String,
}

// --- Room schemas ---

#[derive(ToSchema)]
#[schema(example = json!({"name": "Movie Night", "description": "Watch movies together", "password": ""}))]
pub struct CreateRoomRequestSchema {
    pub name: String,
    /// Room description (max 500 characters)
    #[schema(default = "")]
    pub description: String,
    #[schema(default = "")]
    pub password: String,
}

#[derive(ToSchema)]
pub struct CreateRoomResponseSchema {
    pub room: Option<RoomSchema>,
}

#[derive(ToSchema)]
pub struct GetRoomResponseSchema {
    pub room: Option<RoomSchema>,
    pub playback_state: Option<PlaybackStateSchema>,
}

#[derive(ToSchema)]
#[schema(example = json!({"password": ""}))]
pub struct JoinRoomRequestSchema {
    #[schema(default = "")]
    pub password: String,
}

#[derive(ToSchema)]
pub struct JoinRoomResponseSchema {
    pub room: Option<RoomSchema>,
    pub playback_state: Option<PlaybackStateSchema>,
    pub members: Vec<RoomMemberSchema>,
}

#[derive(ToSchema)]
pub struct LeaveRoomResponseSchema {
    pub success: bool,
}

#[derive(ToSchema)]
pub struct DeleteRoomResponseSchema {
    pub success: bool,
}

#[derive(ToSchema)]
pub struct ListRoomsResponseSchema {
    pub rooms: Vec<RoomSchema>,
    pub total: i32,
}

#[derive(ToSchema)]
pub struct GetRoomMembersResponseSchema {
    pub members: Vec<RoomMemberSchema>,
}

#[derive(ToSchema)]
pub struct CheckRoomResponseSchema {
    pub exists: bool,
    pub requires_password: bool,
    pub name: String,
}

// --- Media schemas ---

#[derive(ToSchema)]
#[schema(example = json!({"url": "https://example.com/video.mp4", "provider": "", "title": "My Video"}))]
pub struct AddMediaRequestSchema {
    pub url: String,
    #[schema(default = "")]
    pub provider: String,
    pub title: String,
}

#[derive(ToSchema)]
pub struct AddMediaResponseSchema {
    pub media: Option<MediaSchema>,
}

#[derive(ToSchema)]
pub struct ListPlaylistResponseSchema {
    pub media: Vec<MediaSchema>,
    pub total: i32,
}

// --- Playback schemas ---

#[derive(ToSchema)]
#[schema(example = json!({"position": 42.5}))]
pub struct SeekRequestSchema {
    pub position: f64,
}

#[derive(ToSchema)]
#[schema(example = json!({"speed": 1.5}))]
pub struct ChangeSpeedRequestSchema {
    pub speed: f64,
}

#[derive(ToSchema)]
#[schema(example = json!({"media_id": "media_abc"}))]
pub struct SwitchMediaRequestSchema {
    pub media_id: String,
}

#[derive(ToSchema)]
pub struct GetPlaybackStateResponseSchema {
    pub playback_state: Option<PlaybackStateSchema>,
}

// --- User schemas ---

#[derive(ToSchema)]
pub struct GetProfileResponseSchema {
    pub user: Option<UserSchema>,
}

#[derive(ToSchema)]
#[schema(example = json!({"new_username": "bob"}))]
pub struct SetUsernameRequestSchema {
    pub new_username: String,
}

#[derive(ToSchema)]
pub struct SetUsernameResponseSchema {
    pub success: bool,
}

#[derive(ToSchema)]
#[schema(example = json!({"new_password": "newsecret123"}))]
pub struct SetPasswordRequestSchema {
    pub new_password: String,
}

#[derive(ToSchema)]
pub struct SetPasswordResponseSchema {
    pub success: bool,
}

// --- WebRTC schemas ---

#[derive(ToSchema)]
pub struct IceServerSchema {
    pub urls: Vec<String>,
    pub username: Option<String>,
    pub credential: Option<String>,
}

#[derive(ToSchema)]
pub struct GetIceServersResponseSchema {
    pub servers: Vec<IceServerSchema>,
}

// --- Chat schemas ---

#[derive(ToSchema)]
#[schema(example = json!({"content": "Hello everyone!"}))]
pub struct SendMessageRequestSchema {
    pub content: String,
}

#[derive(ToSchema)]
pub struct SendMessageResponseSchema {
    pub id: String,
    pub room_id: String,
    pub user_id: String,
    pub username: String,
    pub content: String,
    pub created_at: String,
}

#[derive(ToSchema)]
pub struct ChatHistoryResponseSchema {
    pub messages: Vec<ChatMessageSchema>,
}

#[derive(ToSchema)]
pub struct ChatMessageSchema {
    pub id: String,
    pub room_id: String,
    pub user_id: String,
    pub username: String,
    pub content: String,
    pub created_at: String,
}

// --- Health / Public schemas ---

#[derive(ToSchema)]
pub struct PublicSettingsSchema {
    pub signup_enabled: bool,
    pub allow_room_creation: bool,
    pub max_rooms_per_user: i64,
    pub max_members_per_room: i64,
}

#[derive(ToSchema)]
pub struct ErrorResponseSchema {
    pub error: String,
    pub status: u16,
}

// --- Admin schemas ---

#[derive(ToSchema)]
#[schema(example = json!({"active_users": 42, "total_rooms": 10, "total_users": 100, "uptime_seconds": 86400}))]
pub struct AdminStatsSchema {
    pub active_users: i64,
    pub total_rooms: i64,
    pub total_users: i64,
    pub uptime_seconds: i64,
}

#[derive(ToSchema)]
#[schema(example = json!({"settings": {"signup_enabled": true, "max_rooms_per_user": 5}}))]
pub struct AdminSettingsSchema {
    pub settings: serde_json::Value,
}

#[derive(ToSchema)]
#[schema(example = json!({"settings": {"signup_enabled": false}}))]
pub struct AdminUpdateSettingsRequestSchema {
    pub settings: serde_json::Value,
}

#[derive(ToSchema)]
#[schema(example = json!({"users": [], "total": 0}))]
pub struct AdminUsersListSchema {
    pub users: Vec<UserSchema>,
    pub total: i64,
}

#[derive(ToSchema)]
#[schema(example = json!({"username": "newuser", "password": "secret123", "email": "user@example.com"}))]
pub struct AdminCreateUserRequestSchema {
    pub username: String,
    pub password: String,
    pub email: String,
}

#[derive(ToSchema)]
#[schema(example = json!({"role": "admin"}))]
pub struct AdminSetRoleRequestSchema {
    pub role: String,
}

#[derive(ToSchema)]
#[schema(example = json!({"password": "newpassword123"}))]
pub struct AdminSetPasswordRequestSchema {
    pub password: String,
}

#[derive(ToSchema)]
#[schema(example = json!({"username": "newname"}))]
pub struct AdminSetUsernameRequestSchema {
    pub username: String,
}

#[derive(ToSchema)]
#[schema(example = json!({"rooms": [], "total": 0}))]
pub struct AdminRoomsListSchema {
    pub rooms: Vec<RoomSchema>,
    pub total: i64,
}

#[derive(ToSchema)]
#[schema(example = json!({"to": "user@example.com", "subject": "Test", "body": "Hello"}))]
pub struct AdminTestEmailRequestSchema {
    pub to: String,
    pub subject: String,
    pub body: String,
}

#[derive(ToSchema)]
#[schema(example = json!({"name": "my-provider", "type": "bilibili", "enabled": true, "config": {}}))]
pub struct ProviderSchema {
    pub name: String,
    #[schema(rename = "type")]
    pub provider_type: String,
    pub enabled: bool,
    pub config: serde_json::Value,
}

#[derive(ToSchema)]
#[schema(example = json!({"providers": []}))]
pub struct ProvidersListSchema {
    pub providers: Vec<ProviderSchema>,
}

#[derive(ToSchema)]
#[schema(example = json!({"name": "my-provider", "type": "bilibili", "config": {}}))]
pub struct CreateProviderRequestSchema {
    pub name: String,
    #[schema(rename = "type")]
    pub provider_type: String,
    pub config: serde_json::Value,
}

#[derive(ToSchema)]
#[schema(example = json!({"config": {}}))]
pub struct UpdateProviderRequestSchema {
    pub config: serde_json::Value,
}

// --- Email schemas ---

#[derive(ToSchema)]
#[schema(example = json!({"email": "user@example.com"}))]
pub struct EmailSendVerifyRequestSchema {
    pub email: String,
}

#[derive(ToSchema)]
#[schema(example = json!({"email": "user@example.com", "code": "123456"}))]
pub struct EmailConfirmVerifyRequestSchema {
    pub email: String,
    pub code: String,
}

#[derive(ToSchema)]
#[schema(example = json!({"email": "user@example.com"}))]
pub struct EmailPasswordResetRequestSchema {
    pub email: String,
}

#[derive(ToSchema)]
#[schema(example = json!({"email": "user@example.com", "code": "123456", "new_password": "newsecret"}))]
pub struct EmailPasswordConfirmRequestSchema {
    pub email: String,
    pub code: String,
    pub new_password: String,
}

// --- Room member management schemas ---

#[derive(ToSchema)]
#[schema(example = json!({"permissions": 7}))]
pub struct SetMemberPermissionsRequestSchema {
    pub permissions: i64,
}

// --- Notification schemas ---

#[derive(ToSchema)]
#[schema(example = json!({"id": "notif_abc", "type": "info", "title": "Welcome", "message": "Welcome to SyncTV", "read": false, "created_at": 1700000000}))]
pub struct NotificationSchema {
    pub id: String,
    #[schema(rename = "type")]
    pub notification_type: String,
    pub title: String,
    pub message: String,
    pub read: bool,
    pub created_at: i64,
}

#[derive(ToSchema)]
#[schema(example = json!({"notifications": [], "total": 0}))]
pub struct NotificationsListSchema {
    pub notifications: Vec<NotificationSchema>,
    pub total: i64,
}

#[derive(ToSchema)]
#[schema(example = json!({"ids": ["notif_abc", "notif_def"]}))]
pub struct MarkNotificationsReadRequestSchema {
    pub ids: Vec<String>,
}

// --- OAuth2 schemas ---

#[derive(ToSchema)]
#[schema(example = json!({"authorize_url": "https://provider.com/authorize?..."}))]
pub struct OAuth2AuthorizeResponseSchema {
    pub authorize_url: String,
}

#[derive(ToSchema)]
#[schema(example = json!({"user": null, "access_token": "eyJ...", "refresh_token": "eyJ..."}))]
pub struct OAuth2CallbackResponseSchema {
    pub user: Option<UserSchema>,
    pub access_token: String,
    pub refresh_token: String,
}

#[derive(ToSchema)]
#[schema(example = json!({"providers": ["google", "github"]}))]
pub struct OAuth2ProvidersListSchema {
    pub providers: Vec<String>,
}

// --- Provider schemas ---

#[derive(ToSchema)]
#[schema(example = json!({"url": "https://bilibili.com/video/BV..."}))]
pub struct BilibiliParseRequestSchema {
    pub url: String,
}

#[derive(ToSchema)]
#[schema(example = json!({"title": "Video Title", "url": "https://cdn.bilibili.com/..."}))]
pub struct BilibiliParseResponseSchema {
    pub title: String,
    pub url: String,
}

#[derive(ToSchema)]
#[schema(example = json!({"qr_url": "https://passport.bilibili.com/qrcode/...", "token": "abc123"}))]
pub struct BilibiliQrResponseSchema {
    pub qr_url: String,
    pub token: String,
}

#[derive(ToSchema)]
#[schema(example = json!({"token": "abc123"}))]
pub struct BilibiliQrLoginRequestSchema {
    pub token: String,
}

#[derive(ToSchema)]
#[schema(example = json!({"server_url": "https://alist.example.com", "username": "admin", "password": "secret"}))]
pub struct AlistLoginRequestSchema {
    pub server_url: String,
    pub username: String,
    pub password: String,
}

#[derive(ToSchema)]
#[schema(example = json!({"token": "alist_token_abc123"}))]
pub struct AlistLoginResponseSchema {
    pub token: String,
}

#[derive(ToSchema)]
#[schema(example = json!({"path": "/movies"}))]
pub struct AlistListRequestSchema {
    pub path: String,
}

#[derive(ToSchema)]
#[schema(example = json!({"files": [{"name": "movie.mp4", "size": 1024000, "is_dir": false}]}))]
pub struct AlistListResponseSchema {
    pub files: Vec<serde_json::Value>,
}

#[derive(ToSchema)]
#[schema(example = json!({"username": "user123", "logged_in": true}))]
pub struct ProviderMeResponseSchema {
    pub username: String,
    pub logged_in: bool,
}

#[derive(ToSchema)]
#[schema(example = json!({"server_url": "https://emby.example.com", "username": "admin", "password": "secret"}))]
pub struct EmbyLoginRequestSchema {
    pub server_url: String,
    pub username: String,
    pub password: String,
}

#[derive(ToSchema)]
#[schema(example = json!({"token": "emby_token_abc123"}))]
pub struct EmbyLoginResponseSchema {
    pub token: String,
}

#[derive(ToSchema)]
#[schema(example = json!({"parent_id": "", "page": 1, "limit": 20}))]
pub struct EmbyListRequestSchema {
    pub parent_id: String,
    pub page: i32,
    pub limit: i32,
}

#[derive(ToSchema)]
#[schema(example = json!({"items": [{"id": "1", "name": "Movie", "type": "Movie"}], "total": 1}))]
pub struct EmbyListResponseSchema {
    pub items: Vec<serde_json::Value>,
    pub total: i64,
}

// ============== Security modifier ==============

struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        if let Some(components) = openapi.components.as_mut() {
            components.add_security_scheme(
                "bearer_auth",
                SecurityScheme::Http(
                    HttpBuilder::new()
                        .scheme(HttpAuthScheme::Bearer)
                        .bearer_format("JWT")
                        .build(),
                ),
            );
        }
    }
}

// ============== OpenAPI doc ==============

#[derive(OpenApi)]
#[openapi(
    info(
        title = "SyncTV API",
        version = "0.1.0",
        description = "SyncTV - Real-time synchronized video watching platform.\n\nThis API provides endpoints for authentication, room management, media/playlist control, playback synchronization, chat, and WebRTC configuration.",
        license(name = "MIT OR Apache-2.0"),
    ),
    paths(
        // Health
        path_health,
        path_metrics,
        // Auth
        path_register,
        path_login,
        path_refresh_token,
        // User
        path_get_me,
        path_logout,
        path_update_username,
        path_update_password,
        path_get_joined_rooms,
        // Room discovery
        path_check_room,
        path_list_rooms,
        path_hot_rooms,
        // Room management
        path_create_room,
        path_get_room,
        path_join_room,
        path_leave_room,
        path_delete_room,
        path_get_room_members,
        path_get_room_settings,
        // Room member management
        path_kick_member,
        path_ban_member,
        path_unban_member,
        path_set_member_permissions,
        // Media
        path_add_media,
        path_remove_media,
        path_get_playlist,
        // Playback
        path_play,
        path_pause,
        path_seek,
        path_change_speed,
        path_switch_media,
        path_get_playback_state,
        // Chat
        path_send_chat,
        path_get_chat_history,
        // WebRTC
        path_get_ice_servers,
        // Public
        path_public_settings,
        // Admin
        path_admin_stats,
        path_admin_get_settings,
        path_admin_update_settings,
        path_admin_get_settings_group,
        path_admin_test_email,
        path_admin_list_users,
        path_admin_create_user,
        path_admin_get_user,
        path_admin_delete_user,
        path_admin_set_user_role,
        path_admin_set_user_password,
        path_admin_set_user_username,
        path_admin_ban_user,
        path_admin_unban_user,
        path_admin_approve_user,
        path_admin_list_rooms,
        path_admin_get_room,
        path_admin_delete_room,
        path_admin_ban_room,
        path_admin_unban_room,
        path_admin_approve_room,
        path_admin_list_providers,
        path_admin_create_provider,
        path_admin_update_provider,
        path_admin_delete_provider,
        path_admin_reconnect_provider,
        path_admin_enable_provider,
        path_admin_disable_provider,
        // Email
        path_email_verify_send,
        path_email_verify_confirm,
        path_email_password_reset,
        path_email_password_confirm,
        // Notifications
        path_list_notifications,
        path_get_notification,
        path_mark_notifications_read,
        path_mark_all_notifications_read,
        path_delete_notification,
        // OAuth2
        path_oauth2_authorize,
        path_oauth2_callback,
        path_oauth2_providers,
        // Live
        path_live_flv,
        path_live_hls,
        // Providers
        path_bilibili_parse,
        path_bilibili_qr_get,
        path_bilibili_qr_login,
        path_bilibili_me,
        path_alist_login,
        path_alist_list,
        path_alist_me,
        path_emby_login,
        path_emby_list,
        path_emby_me,
    ),
    components(schemas(
        UserSchema,
        RoomSchema,
        MediaSchema,
        PlaybackStateSchema,
        RoomMemberSchema,
        RegisterRequestSchema,
        RegisterResponseSchema,
        LoginRequestSchema,
        LoginResponseSchema,
        RefreshTokenRequestSchema,
        RefreshTokenResponseSchema,
        CreateRoomRequestSchema,
        CreateRoomResponseSchema,
        GetRoomResponseSchema,
        JoinRoomRequestSchema,
        JoinRoomResponseSchema,
        LeaveRoomResponseSchema,
        DeleteRoomResponseSchema,
        ListRoomsResponseSchema,
        GetRoomMembersResponseSchema,
        CheckRoomResponseSchema,
        AddMediaRequestSchema,
        AddMediaResponseSchema,
        ListPlaylistResponseSchema,
        SeekRequestSchema,
        ChangeSpeedRequestSchema,
        SwitchMediaRequestSchema,
        GetPlaybackStateResponseSchema,
        GetProfileResponseSchema,
        SetUsernameRequestSchema,
        SetUsernameResponseSchema,
        SetPasswordRequestSchema,
        SetPasswordResponseSchema,
        IceServerSchema,
        GetIceServersResponseSchema,
        SendMessageRequestSchema,
        SendMessageResponseSchema,
        ChatHistoryResponseSchema,
        ChatMessageSchema,
        PublicSettingsSchema,
        ErrorResponseSchema,
        // Admin schemas
        AdminStatsSchema,
        AdminSettingsSchema,
        AdminUpdateSettingsRequestSchema,
        AdminUsersListSchema,
        AdminCreateUserRequestSchema,
        AdminSetRoleRequestSchema,
        AdminSetPasswordRequestSchema,
        AdminSetUsernameRequestSchema,
        AdminRoomsListSchema,
        AdminTestEmailRequestSchema,
        ProviderSchema,
        ProvidersListSchema,
        CreateProviderRequestSchema,
        UpdateProviderRequestSchema,
        // Email schemas
        EmailSendVerifyRequestSchema,
        EmailConfirmVerifyRequestSchema,
        EmailPasswordResetRequestSchema,
        EmailPasswordConfirmRequestSchema,
        // Room member management schemas
        SetMemberPermissionsRequestSchema,
        // Notification schemas
        NotificationSchema,
        NotificationsListSchema,
        MarkNotificationsReadRequestSchema,
        // OAuth2 schemas
        OAuth2AuthorizeResponseSchema,
        OAuth2CallbackResponseSchema,
        OAuth2ProvidersListSchema,
        // Provider schemas
        BilibiliParseRequestSchema,
        BilibiliParseResponseSchema,
        BilibiliQrResponseSchema,
        BilibiliQrLoginRequestSchema,
        AlistLoginRequestSchema,
        AlistLoginResponseSchema,
        AlistListRequestSchema,
        AlistListResponseSchema,
        ProviderMeResponseSchema,
        EmbyLoginRequestSchema,
        EmbyLoginResponseSchema,
        EmbyListRequestSchema,
        EmbyListResponseSchema,
    )),
    modifiers(&SecurityAddon),
    tags(
        (name = "health", description = "Health check and monitoring"),
        (name = "auth", description = "Authentication (register, login, token refresh)"),
        (name = "user", description = "User profile and account management"),
        (name = "rooms", description = "Room discovery and management"),
        (name = "media", description = "Media/playlist management"),
        (name = "playback", description = "Playback synchronization control"),
        (name = "chat", description = "Chat and danmaku messaging"),
        (name = "webrtc", description = "WebRTC configuration"),
        (name = "public", description = "Public endpoints (no auth required)"),
        (name = "admin", description = "Admin endpoints for server management"),
        (name = "email", description = "Email verification and password reset"),
        (name = "notifications", description = "User notifications"),
        (name = "oauth2", description = "OAuth2 authentication providers"),
        (name = "live", description = "Live streaming endpoints"),
        (name = "providers", description = "Third-party content provider integrations"),
    )
)]
pub struct ApiDoc;

// ============== Path definitions ==============

#[utoipa::path(
    get,
    path = "/health",
    tag = "health",
    responses((status = 200, description = "Server is healthy", body = String))
)]
pub async fn path_health() {}

#[utoipa::path(
    get,
    path = "/metrics",
    tag = "health",
    responses((status = 200, description = "Prometheus metrics", content_type = "text/plain"))
)]
pub async fn path_metrics() {}

// --- Auth paths ---

#[utoipa::path(
    post,
    path = "/api/auth/register",
    tag = "auth",
    request_body = RegisterRequestSchema,
    responses(
        (status = 200, description = "Registration successful", body = RegisterResponseSchema),
        (status = 400, description = "Bad request", body = ErrorResponseSchema),
    )
)]
pub async fn path_register() {}

#[utoipa::path(
    post,
    path = "/api/auth/login",
    tag = "auth",
    request_body = LoginRequestSchema,
    responses(
        (status = 200, description = "Login successful", body = LoginResponseSchema),
        (status = 401, description = "Invalid credentials", body = ErrorResponseSchema),
    )
)]
pub async fn path_login() {}

#[utoipa::path(
    post,
    path = "/api/auth/refresh",
    tag = "auth",
    request_body = RefreshTokenRequestSchema,
    responses(
        (status = 200, description = "Token refreshed", body = RefreshTokenResponseSchema),
        (status = 401, description = "Invalid refresh token", body = ErrorResponseSchema),
    )
)]
pub async fn path_refresh_token() {}

// --- User paths ---

#[utoipa::path(
    get,
    path = "/api/user/me",
    tag = "user",
    security(("bearer_auth" = [])),
    responses(
        (status = 200, description = "Current user profile", body = GetProfileResponseSchema),
        (status = 401, description = "Unauthorized", body = ErrorResponseSchema),
    )
)]
pub async fn path_get_me() {}

#[utoipa::path(
    post,
    path = "/api/user/logout",
    tag = "user",
    security(("bearer_auth" = [])),
    responses(
        (status = 200, description = "Logout successful"),
    )
)]
pub async fn path_logout() {}

#[utoipa::path(
    post,
    path = "/api/user/username",
    tag = "user",
    security(("bearer_auth" = [])),
    request_body = SetUsernameRequestSchema,
    responses(
        (status = 200, description = "Username updated", body = SetUsernameResponseSchema),
        (status = 400, description = "Bad request", body = ErrorResponseSchema),
    )
)]
pub async fn path_update_username() {}

#[utoipa::path(
    post,
    path = "/api/user/password",
    tag = "user",
    security(("bearer_auth" = [])),
    request_body = SetPasswordRequestSchema,
    responses(
        (status = 200, description = "Password updated", body = SetPasswordResponseSchema),
        (status = 400, description = "Bad request", body = ErrorResponseSchema),
    )
)]
pub async fn path_update_password() {}

#[utoipa::path(
    get,
    path = "/api/user/rooms",
    tag = "user",
    security(("bearer_auth" = [])),
    responses(
        (status = 200, description = "List of joined rooms", body = ListRoomsResponseSchema),
    )
)]
pub async fn path_get_joined_rooms() {}

// --- Room discovery paths ---

#[utoipa::path(
    get,
    path = "/api/room/check/{room_id}",
    tag = "rooms",
    params(("room_id" = String, Path, description = "Room ID")),
    responses(
        (status = 200, description = "Room check result", body = CheckRoomResponseSchema),
    )
)]
pub async fn path_check_room() {}

#[utoipa::path(
    get,
    path = "/api/room/list",
    tag = "rooms",
    responses(
        (status = 200, description = "List of rooms", body = ListRoomsResponseSchema),
    )
)]
pub async fn path_list_rooms() {}

#[utoipa::path(
    get,
    path = "/api/room/hot",
    tag = "rooms",
    responses(
        (status = 200, description = "Hot rooms sorted by activity", body = ListRoomsResponseSchema),
    )
)]
pub async fn path_hot_rooms() {}

// --- Room management paths ---

#[utoipa::path(
    post,
    path = "/api/rooms",
    tag = "rooms",
    security(("bearer_auth" = [])),
    request_body = CreateRoomRequestSchema,
    responses(
        (status = 200, description = "Room created", body = CreateRoomResponseSchema),
        (status = 400, description = "Bad request", body = ErrorResponseSchema),
    )
)]
pub async fn path_create_room() {}

#[utoipa::path(
    get,
    path = "/api/rooms/{room_id}",
    tag = "rooms",
    security(("bearer_auth" = [])),
    params(("room_id" = String, Path, description = "Room ID")),
    responses(
        (status = 200, description = "Room details", body = GetRoomResponseSchema),
        (status = 404, description = "Room not found", body = ErrorResponseSchema),
    )
)]
pub async fn path_get_room() {}

#[utoipa::path(
    post,
    path = "/api/rooms/{room_id}/join",
    tag = "rooms",
    security(("bearer_auth" = [])),
    params(("room_id" = String, Path, description = "Room ID")),
    request_body = JoinRoomRequestSchema,
    responses(
        (status = 200, description = "Joined room", body = JoinRoomResponseSchema),
        (status = 404, description = "Room not found", body = ErrorResponseSchema),
    )
)]
pub async fn path_join_room() {}

#[utoipa::path(
    post,
    path = "/api/rooms/{room_id}/leave",
    tag = "rooms",
    security(("bearer_auth" = [])),
    params(("room_id" = String, Path, description = "Room ID")),
    responses(
        (status = 200, description = "Left room", body = LeaveRoomResponseSchema),
    )
)]
pub async fn path_leave_room() {}

#[utoipa::path(
    delete,
    path = "/api/rooms/{room_id}",
    tag = "rooms",
    security(("bearer_auth" = [])),
    params(("room_id" = String, Path, description = "Room ID")),
    responses(
        (status = 200, description = "Room deleted", body = DeleteRoomResponseSchema),
        (status = 403, description = "Forbidden", body = ErrorResponseSchema),
    )
)]
pub async fn path_delete_room() {}

#[utoipa::path(
    get,
    path = "/api/rooms/{room_id}/members",
    tag = "rooms",
    security(("bearer_auth" = [])),
    params(("room_id" = String, Path, description = "Room ID")),
    responses(
        (status = 200, description = "Room members", body = GetRoomMembersResponseSchema),
    )
)]
pub async fn path_get_room_members() {}

#[utoipa::path(
    get,
    path = "/api/rooms/{room_id}/settings",
    tag = "rooms",
    params(("room_id" = String, Path, description = "Room ID")),
    responses(
        (status = 200, description = "Room settings"),
    )
)]
pub async fn path_get_room_settings() {}

// --- Media paths ---

#[utoipa::path(
    post,
    path = "/api/rooms/{room_id}/media",
    tag = "media",
    security(("bearer_auth" = [])),
    params(("room_id" = String, Path, description = "Room ID")),
    request_body = AddMediaRequestSchema,
    responses(
        (status = 200, description = "Media added", body = AddMediaResponseSchema),
        (status = 400, description = "Bad request", body = ErrorResponseSchema),
    )
)]
pub async fn path_add_media() {}

#[utoipa::path(
    delete,
    path = "/api/rooms/{room_id}/media/{media_id}",
    tag = "media",
    security(("bearer_auth" = [])),
    params(
        ("room_id" = String, Path, description = "Room ID"),
        ("media_id" = String, Path, description = "Media ID"),
    ),
    responses(
        (status = 200, description = "Media removed"),
        (status = 404, description = "Media not found", body = ErrorResponseSchema),
    )
)]
pub async fn path_remove_media() {}

#[utoipa::path(
    get,
    path = "/api/rooms/{room_id}/media",
    tag = "media",
    security(("bearer_auth" = [])),
    params(("room_id" = String, Path, description = "Room ID")),
    responses(
        (status = 200, description = "Playlist contents", body = ListPlaylistResponseSchema),
    )
)]
pub async fn path_get_playlist() {}

// --- Playback paths ---

#[utoipa::path(
    post,
    path = "/api/rooms/{room_id}/playback/play",
    tag = "playback",
    security(("bearer_auth" = [])),
    params(("room_id" = String, Path, description = "Room ID")),
    responses((status = 200, description = "Playback resumed"))
)]
pub async fn path_play() {}

#[utoipa::path(
    post,
    path = "/api/rooms/{room_id}/playback/pause",
    tag = "playback",
    security(("bearer_auth" = [])),
    params(("room_id" = String, Path, description = "Room ID")),
    responses((status = 200, description = "Playback paused"))
)]
pub async fn path_pause() {}

#[utoipa::path(
    post,
    path = "/api/rooms/{room_id}/playback/seek",
    tag = "playback",
    security(("bearer_auth" = [])),
    params(("room_id" = String, Path, description = "Room ID")),
    request_body = SeekRequestSchema,
    responses((status = 200, description = "Seeked to position"))
)]
pub async fn path_seek() {}

#[utoipa::path(
    post,
    path = "/api/rooms/{room_id}/playback/speed",
    tag = "playback",
    security(("bearer_auth" = [])),
    params(("room_id" = String, Path, description = "Room ID")),
    request_body = ChangeSpeedRequestSchema,
    responses((status = 200, description = "Speed changed"))
)]
pub async fn path_change_speed() {}

#[utoipa::path(
    post,
    path = "/api/rooms/{room_id}/playback/switch",
    tag = "playback",
    security(("bearer_auth" = [])),
    params(("room_id" = String, Path, description = "Room ID")),
    request_body = SwitchMediaRequestSchema,
    responses((status = 200, description = "Switched to media"))
)]
pub async fn path_switch_media() {}

#[utoipa::path(
    get,
    path = "/api/rooms/{room_id}/playback",
    tag = "playback",
    security(("bearer_auth" = [])),
    params(("room_id" = String, Path, description = "Room ID")),
    responses(
        (status = 200, description = "Current playback state", body = GetPlaybackStateResponseSchema),
    )
)]
pub async fn path_get_playback_state() {}

// --- Chat paths ---

#[utoipa::path(
    post,
    path = "/api/rooms/{room_id}/chat",
    tag = "chat",
    security(("bearer_auth" = [])),
    params(("room_id" = String, Path, description = "Room ID")),
    request_body = SendMessageRequestSchema,
    responses(
        (status = 200, description = "Message sent", body = SendMessageResponseSchema),
    )
)]
pub async fn path_send_chat() {}

#[utoipa::path(
    get,
    path = "/api/rooms/{room_id}/chat",
    tag = "chat",
    security(("bearer_auth" = [])),
    params(
        ("room_id" = String, Path, description = "Room ID"),
        ("before" = Option<String>, Query, description = "ISO 8601 datetime cursor for pagination"),
        ("limit" = Option<i32>, Query, description = "Max messages to return (default 50, max 100)"),
    ),
    responses(
        (status = 200, description = "Chat history", body = ChatHistoryResponseSchema),
    )
)]
pub async fn path_get_chat_history() {}

// --- WebRTC paths ---

#[utoipa::path(
    get,
    path = "/api/rooms/{room_id}/webrtc/ice-servers",
    tag = "webrtc",
    security(("bearer_auth" = [])),
    params(("room_id" = String, Path, description = "Room ID")),
    responses(
        (status = 200, description = "ICE server configuration", body = GetIceServersResponseSchema),
        (status = 403, description = "Not a room member", body = ErrorResponseSchema),
    )
)]
pub async fn path_get_ice_servers() {}

// --- Public paths ---

#[utoipa::path(
    get,
    path = "/api/public/settings",
    tag = "public",
    responses(
        (status = 200, description = "Public server settings", body = PublicSettingsSchema),
    )
)]
pub async fn path_public_settings() {}

// --- Room member management paths ---

#[utoipa::path(
    post,
    path = "/api/rooms/{room_id}/members/{user_id}/kick",
    tag = "rooms",
    security(("bearer_auth" = [])),
    params(
        ("room_id" = String, Path, description = "Room ID"),
        ("user_id" = String, Path, description = "User ID"),
    ),
    responses(
        (status = 200, description = "Member kicked"),
        (status = 403, description = "Forbidden", body = ErrorResponseSchema),
        (status = 404, description = "Member not found", body = ErrorResponseSchema),
    )
)]
pub async fn path_kick_member() {}

#[utoipa::path(
    post,
    path = "/api/rooms/{room_id}/members/{user_id}/ban",
    tag = "rooms",
    security(("bearer_auth" = [])),
    params(
        ("room_id" = String, Path, description = "Room ID"),
        ("user_id" = String, Path, description = "User ID"),
    ),
    responses(
        (status = 200, description = "Member banned"),
        (status = 403, description = "Forbidden", body = ErrorResponseSchema),
    )
)]
pub async fn path_ban_member() {}

#[utoipa::path(
    post,
    path = "/api/rooms/{room_id}/members/{user_id}/unban",
    tag = "rooms",
    security(("bearer_auth" = [])),
    params(
        ("room_id" = String, Path, description = "Room ID"),
        ("user_id" = String, Path, description = "User ID"),
    ),
    responses(
        (status = 200, description = "Member unbanned"),
        (status = 403, description = "Forbidden", body = ErrorResponseSchema),
    )
)]
pub async fn path_unban_member() {}

#[utoipa::path(
    post,
    path = "/api/rooms/{room_id}/members/{user_id}/permissions",
    tag = "rooms",
    security(("bearer_auth" = [])),
    params(
        ("room_id" = String, Path, description = "Room ID"),
        ("user_id" = String, Path, description = "User ID"),
    ),
    request_body = SetMemberPermissionsRequestSchema,
    responses(
        (status = 200, description = "Permissions updated"),
        (status = 403, description = "Forbidden", body = ErrorResponseSchema),
    )
)]
pub async fn path_set_member_permissions() {}

// --- Admin paths ---

#[utoipa::path(
    get,
    path = "/api/admin/stats",
    tag = "admin",
    security(("bearer_auth" = [])),
    responses(
        (status = 200, description = "Server statistics", body = AdminStatsSchema),
        (status = 403, description = "Forbidden", body = ErrorResponseSchema),
    )
)]
pub async fn path_admin_stats() {}

#[utoipa::path(
    get,
    path = "/api/admin/settings",
    tag = "admin",
    security(("bearer_auth" = [])),
    responses(
        (status = 200, description = "All admin settings", body = AdminSettingsSchema),
        (status = 403, description = "Forbidden", body = ErrorResponseSchema),
    )
)]
pub async fn path_admin_get_settings() {}

#[utoipa::path(
    post,
    path = "/api/admin/settings",
    tag = "admin",
    security(("bearer_auth" = [])),
    request_body = AdminUpdateSettingsRequestSchema,
    responses(
        (status = 200, description = "Settings updated"),
        (status = 403, description = "Forbidden", body = ErrorResponseSchema),
    )
)]
pub async fn path_admin_update_settings() {}

#[utoipa::path(
    get,
    path = "/api/admin/settings/{group}",
    tag = "admin",
    security(("bearer_auth" = [])),
    params(("group" = String, Path, description = "Settings group name")),
    responses(
        (status = 200, description = "Settings for group", body = AdminSettingsSchema),
        (status = 403, description = "Forbidden", body = ErrorResponseSchema),
    )
)]
pub async fn path_admin_get_settings_group() {}

#[utoipa::path(
    post,
    path = "/api/admin/email/test",
    tag = "admin",
    security(("bearer_auth" = [])),
    request_body = AdminTestEmailRequestSchema,
    responses(
        (status = 200, description = "Test email sent"),
        (status = 403, description = "Forbidden", body = ErrorResponseSchema),
    )
)]
pub async fn path_admin_test_email() {}

#[utoipa::path(
    get,
    path = "/api/admin/users",
    tag = "admin",
    security(("bearer_auth" = [])),
    responses(
        (status = 200, description = "List of users", body = AdminUsersListSchema),
        (status = 403, description = "Forbidden", body = ErrorResponseSchema),
    )
)]
pub async fn path_admin_list_users() {}

#[utoipa::path(
    post,
    path = "/api/admin/users",
    tag = "admin",
    security(("bearer_auth" = [])),
    request_body = AdminCreateUserRequestSchema,
    responses(
        (status = 200, description = "User created", body = UserSchema),
        (status = 403, description = "Forbidden", body = ErrorResponseSchema),
    )
)]
pub async fn path_admin_create_user() {}

#[utoipa::path(
    get,
    path = "/api/admin/users/{user_id}",
    tag = "admin",
    security(("bearer_auth" = [])),
    params(("user_id" = String, Path, description = "User ID")),
    responses(
        (status = 200, description = "User details", body = UserSchema),
        (status = 403, description = "Forbidden", body = ErrorResponseSchema),
        (status = 404, description = "User not found", body = ErrorResponseSchema),
    )
)]
pub async fn path_admin_get_user() {}

#[utoipa::path(
    delete,
    path = "/api/admin/users/{user_id}",
    tag = "admin",
    security(("bearer_auth" = [])),
    params(("user_id" = String, Path, description = "User ID")),
    responses(
        (status = 200, description = "User deleted"),
        (status = 403, description = "Forbidden", body = ErrorResponseSchema),
    )
)]
pub async fn path_admin_delete_user() {}

#[utoipa::path(
    post,
    path = "/api/admin/users/{user_id}/role",
    tag = "admin",
    security(("bearer_auth" = [])),
    params(("user_id" = String, Path, description = "User ID")),
    request_body = AdminSetRoleRequestSchema,
    responses(
        (status = 200, description = "User role updated"),
        (status = 403, description = "Forbidden", body = ErrorResponseSchema),
    )
)]
pub async fn path_admin_set_user_role() {}

#[utoipa::path(
    post,
    path = "/api/admin/users/{user_id}/password",
    tag = "admin",
    security(("bearer_auth" = [])),
    params(("user_id" = String, Path, description = "User ID")),
    request_body = AdminSetPasswordRequestSchema,
    responses(
        (status = 200, description = "User password updated"),
        (status = 403, description = "Forbidden", body = ErrorResponseSchema),
    )
)]
pub async fn path_admin_set_user_password() {}

#[utoipa::path(
    post,
    path = "/api/admin/users/{user_id}/username",
    tag = "admin",
    security(("bearer_auth" = [])),
    params(("user_id" = String, Path, description = "User ID")),
    request_body = AdminSetUsernameRequestSchema,
    responses(
        (status = 200, description = "Username updated"),
        (status = 403, description = "Forbidden", body = ErrorResponseSchema),
    )
)]
pub async fn path_admin_set_user_username() {}

#[utoipa::path(
    post,
    path = "/api/admin/users/{user_id}/ban",
    tag = "admin",
    security(("bearer_auth" = [])),
    params(("user_id" = String, Path, description = "User ID")),
    responses(
        (status = 200, description = "User banned"),
        (status = 403, description = "Forbidden", body = ErrorResponseSchema),
    )
)]
pub async fn path_admin_ban_user() {}

#[utoipa::path(
    post,
    path = "/api/admin/users/{user_id}/unban",
    tag = "admin",
    security(("bearer_auth" = [])),
    params(("user_id" = String, Path, description = "User ID")),
    responses(
        (status = 200, description = "User unbanned"),
        (status = 403, description = "Forbidden", body = ErrorResponseSchema),
    )
)]
pub async fn path_admin_unban_user() {}

#[utoipa::path(
    post,
    path = "/api/admin/users/{user_id}/approve",
    tag = "admin",
    security(("bearer_auth" = [])),
    params(("user_id" = String, Path, description = "User ID")),
    responses(
        (status = 200, description = "User approved"),
        (status = 403, description = "Forbidden", body = ErrorResponseSchema),
    )
)]
pub async fn path_admin_approve_user() {}

#[utoipa::path(
    get,
    path = "/api/admin/rooms",
    tag = "admin",
    security(("bearer_auth" = [])),
    responses(
        (status = 200, description = "List of rooms", body = AdminRoomsListSchema),
        (status = 403, description = "Forbidden", body = ErrorResponseSchema),
    )
)]
pub async fn path_admin_list_rooms() {}

#[utoipa::path(
    get,
    path = "/api/admin/rooms/{room_id}",
    tag = "admin",
    security(("bearer_auth" = [])),
    params(("room_id" = String, Path, description = "Room ID")),
    responses(
        (status = 200, description = "Room details", body = RoomSchema),
        (status = 403, description = "Forbidden", body = ErrorResponseSchema),
        (status = 404, description = "Room not found", body = ErrorResponseSchema),
    )
)]
pub async fn path_admin_get_room() {}

#[utoipa::path(
    delete,
    path = "/api/admin/rooms/{room_id}",
    tag = "admin",
    security(("bearer_auth" = [])),
    params(("room_id" = String, Path, description = "Room ID")),
    responses(
        (status = 200, description = "Room deleted"),
        (status = 403, description = "Forbidden", body = ErrorResponseSchema),
    )
)]
pub async fn path_admin_delete_room() {}

#[utoipa::path(
    post,
    path = "/api/admin/rooms/{room_id}/ban",
    tag = "admin",
    security(("bearer_auth" = [])),
    params(("room_id" = String, Path, description = "Room ID")),
    responses(
        (status = 200, description = "Room banned"),
        (status = 403, description = "Forbidden", body = ErrorResponseSchema),
    )
)]
pub async fn path_admin_ban_room() {}

#[utoipa::path(
    post,
    path = "/api/admin/rooms/{room_id}/unban",
    tag = "admin",
    security(("bearer_auth" = [])),
    params(("room_id" = String, Path, description = "Room ID")),
    responses(
        (status = 200, description = "Room unbanned"),
        (status = 403, description = "Forbidden", body = ErrorResponseSchema),
    )
)]
pub async fn path_admin_unban_room() {}

#[utoipa::path(
    post,
    path = "/api/admin/rooms/{room_id}/approve",
    tag = "admin",
    security(("bearer_auth" = [])),
    params(("room_id" = String, Path, description = "Room ID")),
    responses(
        (status = 200, description = "Room approved"),
        (status = 403, description = "Forbidden", body = ErrorResponseSchema),
    )
)]
pub async fn path_admin_approve_room() {}

#[utoipa::path(
    get,
    path = "/api/admin/providers",
    tag = "admin",
    security(("bearer_auth" = [])),
    responses(
        (status = 200, description = "List of providers", body = ProvidersListSchema),
        (status = 403, description = "Forbidden", body = ErrorResponseSchema),
    )
)]
pub async fn path_admin_list_providers() {}

#[utoipa::path(
    post,
    path = "/api/admin/providers",
    tag = "admin",
    security(("bearer_auth" = [])),
    request_body = CreateProviderRequestSchema,
    responses(
        (status = 200, description = "Provider created", body = ProviderSchema),
        (status = 403, description = "Forbidden", body = ErrorResponseSchema),
    )
)]
pub async fn path_admin_create_provider() {}

#[utoipa::path(
    put,
    path = "/api/admin/providers/{name}",
    tag = "admin",
    security(("bearer_auth" = [])),
    params(("name" = String, Path, description = "Provider instance name")),
    request_body = UpdateProviderRequestSchema,
    responses(
        (status = 200, description = "Provider updated", body = ProviderSchema),
        (status = 403, description = "Forbidden", body = ErrorResponseSchema),
    )
)]
pub async fn path_admin_update_provider() {}

#[utoipa::path(
    delete,
    path = "/api/admin/providers/{name}",
    tag = "admin",
    security(("bearer_auth" = [])),
    params(("name" = String, Path, description = "Provider instance name")),
    responses(
        (status = 200, description = "Provider deleted"),
        (status = 403, description = "Forbidden", body = ErrorResponseSchema),
    )
)]
pub async fn path_admin_delete_provider() {}

#[utoipa::path(
    post,
    path = "/api/admin/providers/{name}/reconnect",
    tag = "admin",
    security(("bearer_auth" = [])),
    params(("name" = String, Path, description = "Provider instance name")),
    responses(
        (status = 200, description = "Provider reconnected"),
        (status = 403, description = "Forbidden", body = ErrorResponseSchema),
    )
)]
pub async fn path_admin_reconnect_provider() {}

#[utoipa::path(
    post,
    path = "/api/admin/providers/{name}/enable",
    tag = "admin",
    security(("bearer_auth" = [])),
    params(("name" = String, Path, description = "Provider instance name")),
    responses(
        (status = 200, description = "Provider enabled"),
        (status = 403, description = "Forbidden", body = ErrorResponseSchema),
    )
)]
pub async fn path_admin_enable_provider() {}

#[utoipa::path(
    post,
    path = "/api/admin/providers/{name}/disable",
    tag = "admin",
    security(("bearer_auth" = [])),
    params(("name" = String, Path, description = "Provider instance name")),
    responses(
        (status = 200, description = "Provider disabled"),
        (status = 403, description = "Forbidden", body = ErrorResponseSchema),
    )
)]
pub async fn path_admin_disable_provider() {}

// --- Email paths ---

#[utoipa::path(
    post,
    path = "/api/email/verify/send",
    tag = "email",
    security(("bearer_auth" = [])),
    request_body = EmailSendVerifyRequestSchema,
    responses(
        (status = 200, description = "Verification email sent"),
        (status = 400, description = "Bad request", body = ErrorResponseSchema),
    )
)]
pub async fn path_email_verify_send() {}

#[utoipa::path(
    post,
    path = "/api/email/verify/confirm",
    tag = "email",
    request_body = EmailConfirmVerifyRequestSchema,
    responses(
        (status = 200, description = "Email verified"),
        (status = 400, description = "Invalid code", body = ErrorResponseSchema),
    )
)]
pub async fn path_email_verify_confirm() {}

#[utoipa::path(
    post,
    path = "/api/email/password/reset",
    tag = "email",
    request_body = EmailPasswordResetRequestSchema,
    responses(
        (status = 200, description = "Password reset email sent"),
        (status = 400, description = "Bad request", body = ErrorResponseSchema),
    )
)]
pub async fn path_email_password_reset() {}

#[utoipa::path(
    post,
    path = "/api/email/password/confirm",
    tag = "email",
    request_body = EmailPasswordConfirmRequestSchema,
    responses(
        (status = 200, description = "Password reset confirmed"),
        (status = 400, description = "Invalid code", body = ErrorResponseSchema),
    )
)]
pub async fn path_email_password_confirm() {}

// --- Notification paths ---

#[utoipa::path(
    get,
    path = "/api/notifications",
    tag = "notifications",
    security(("bearer_auth" = [])),
    responses(
        (status = 200, description = "List of notifications", body = NotificationsListSchema),
        (status = 401, description = "Unauthorized", body = ErrorResponseSchema),
    )
)]
pub async fn path_list_notifications() {}

#[utoipa::path(
    get,
    path = "/api/notifications/{id}",
    tag = "notifications",
    security(("bearer_auth" = [])),
    params(("id" = String, Path, description = "Notification ID")),
    responses(
        (status = 200, description = "Notification details", body = NotificationSchema),
        (status = 404, description = "Not found", body = ErrorResponseSchema),
    )
)]
pub async fn path_get_notification() {}

#[utoipa::path(
    post,
    path = "/api/notifications/read",
    tag = "notifications",
    security(("bearer_auth" = [])),
    request_body = MarkNotificationsReadRequestSchema,
    responses(
        (status = 200, description = "Notifications marked as read"),
    )
)]
pub async fn path_mark_notifications_read() {}

#[utoipa::path(
    post,
    path = "/api/notifications/read-all",
    tag = "notifications",
    security(("bearer_auth" = [])),
    responses(
        (status = 200, description = "All notifications marked as read"),
    )
)]
pub async fn path_mark_all_notifications_read() {}

#[utoipa::path(
    delete,
    path = "/api/notifications/{id}",
    tag = "notifications",
    security(("bearer_auth" = [])),
    params(("id" = String, Path, description = "Notification ID")),
    responses(
        (status = 200, description = "Notification deleted"),
        (status = 404, description = "Not found", body = ErrorResponseSchema),
    )
)]
pub async fn path_delete_notification() {}

// --- OAuth2 paths ---

#[utoipa::path(
    get,
    path = "/api/oauth2/{provider}/authorize",
    tag = "oauth2",
    params(("provider" = String, Path, description = "OAuth2 provider name (e.g. google, github)")),
    responses(
        (status = 200, description = "Authorization URL", body = OAuth2AuthorizeResponseSchema),
        (status = 400, description = "Unknown provider", body = ErrorResponseSchema),
    )
)]
pub async fn path_oauth2_authorize() {}

#[utoipa::path(
    get,
    path = "/api/oauth2/{provider}/callback",
    tag = "oauth2",
    params(
        ("provider" = String, Path, description = "OAuth2 provider name"),
        ("code" = String, Query, description = "Authorization code"),
        ("state" = String, Query, description = "CSRF state token"),
    ),
    responses(
        (status = 200, description = "OAuth2 login successful", body = OAuth2CallbackResponseSchema),
        (status = 400, description = "Invalid callback", body = ErrorResponseSchema),
    )
)]
pub async fn path_oauth2_callback() {}

#[utoipa::path(
    get,
    path = "/api/oauth2/providers",
    tag = "oauth2",
    responses(
        (status = 200, description = "Available OAuth2 providers", body = OAuth2ProvidersListSchema),
    )
)]
pub async fn path_oauth2_providers() {}

// --- Live streaming paths ---

#[utoipa::path(
    get,
    path = "/api/room/movie/live/flv/{media_id}.flv",
    tag = "live",
    security(("bearer_auth" = [])),
    params(("media_id" = String, Path, description = "Media ID")),
    responses(
        (status = 200, description = "FLV live stream", content_type = "video/x-flv"),
        (status = 404, description = "Stream not found", body = ErrorResponseSchema),
    )
)]
pub async fn path_live_flv() {}

#[utoipa::path(
    get,
    path = "/api/room/movie/live/hls/list/{media_id}.m3u8",
    tag = "live",
    security(("bearer_auth" = [])),
    params(("media_id" = String, Path, description = "Media ID")),
    responses(
        (status = 200, description = "HLS playlist", content_type = "application/vnd.apple.mpegurl"),
        (status = 404, description = "Stream not found", body = ErrorResponseSchema),
    )
)]
pub async fn path_live_hls() {}

// --- Provider paths ---

#[utoipa::path(
    post,
    path = "/api/providers/bilibili/parse",
    tag = "providers",
    security(("bearer_auth" = [])),
    request_body = BilibiliParseRequestSchema,
    responses(
        (status = 200, description = "Parsed Bilibili video", body = BilibiliParseResponseSchema),
        (status = 400, description = "Invalid URL", body = ErrorResponseSchema),
    )
)]
pub async fn path_bilibili_parse() {}

#[utoipa::path(
    get,
    path = "/api/providers/bilibili/login/qr",
    tag = "providers",
    security(("bearer_auth" = [])),
    responses(
        (status = 200, description = "QR code for Bilibili login", body = BilibiliQrResponseSchema),
    )
)]
pub async fn path_bilibili_qr_get() {}

#[utoipa::path(
    post,
    path = "/api/providers/bilibili/login/qr",
    tag = "providers",
    security(("bearer_auth" = [])),
    request_body = BilibiliQrLoginRequestSchema,
    responses(
        (status = 200, description = "QR login result"),
        (status = 400, description = "Login failed", body = ErrorResponseSchema),
    )
)]
pub async fn path_bilibili_qr_login() {}

#[utoipa::path(
    get,
    path = "/api/providers/bilibili/me",
    tag = "providers",
    security(("bearer_auth" = [])),
    responses(
        (status = 200, description = "Current Bilibili user", body = ProviderMeResponseSchema),
        (status = 401, description = "Not logged in", body = ErrorResponseSchema),
    )
)]
pub async fn path_bilibili_me() {}

#[utoipa::path(
    post,
    path = "/api/providers/alist/login",
    tag = "providers",
    security(("bearer_auth" = [])),
    request_body = AlistLoginRequestSchema,
    responses(
        (status = 200, description = "Alist login successful", body = AlistLoginResponseSchema),
        (status = 401, description = "Invalid credentials", body = ErrorResponseSchema),
    )
)]
pub async fn path_alist_login() {}

#[utoipa::path(
    post,
    path = "/api/providers/alist/list",
    tag = "providers",
    security(("bearer_auth" = [])),
    request_body = AlistListRequestSchema,
    responses(
        (status = 200, description = "File listing", body = AlistListResponseSchema),
        (status = 401, description = "Not logged in", body = ErrorResponseSchema),
    )
)]
pub async fn path_alist_list() {}

#[utoipa::path(
    get,
    path = "/api/providers/alist/me",
    tag = "providers",
    security(("bearer_auth" = [])),
    responses(
        (status = 200, description = "Current Alist user", body = ProviderMeResponseSchema),
        (status = 401, description = "Not logged in", body = ErrorResponseSchema),
    )
)]
pub async fn path_alist_me() {}

#[utoipa::path(
    post,
    path = "/api/providers/emby/login",
    tag = "providers",
    security(("bearer_auth" = [])),
    request_body = EmbyLoginRequestSchema,
    responses(
        (status = 200, description = "Emby login successful", body = EmbyLoginResponseSchema),
        (status = 401, description = "Invalid credentials", body = ErrorResponseSchema),
    )
)]
pub async fn path_emby_login() {}

#[utoipa::path(
    post,
    path = "/api/providers/emby/list",
    tag = "providers",
    security(("bearer_auth" = [])),
    request_body = EmbyListRequestSchema,
    responses(
        (status = 200, description = "Media listing", body = EmbyListResponseSchema),
        (status = 401, description = "Not logged in", body = ErrorResponseSchema),
    )
)]
pub async fn path_emby_list() {}

#[utoipa::path(
    get,
    path = "/api/providers/emby/me",
    tag = "providers",
    security(("bearer_auth" = [])),
    responses(
        (status = 200, description = "Current Emby user", body = ProviderMeResponseSchema),
        (status = 401, description = "Not logged in", body = ErrorResponseSchema),
    )
)]
pub async fn path_emby_me() {}
