//! OpenAPI/Swagger documentation
//!
//! Defines the OpenAPI spec for SyncTV's HTTP REST API.
//! Since proto types are auto-generated by prost, we define manual schemas here.

use utoipa::openapi::security::{HttpAuthScheme, HttpBuilder, SecurityScheme};
use utoipa::{Modify, OpenApi, ToSchema};

// ============== Schema types for OpenAPI documentation ==============
// These mirror the proto-generated types but with ToSchema derives.

#[derive(ToSchema)]
#[schema(example = json!({"id": "abc123", "username": "alice", "email": "alice@example.com", "permissions": 7, "created_at": 1700000000}))]
pub struct UserSchema {
    pub id: String,
    pub username: String,
    pub email: String,
    pub permissions: i64,
    pub created_at: i64,
}

#[derive(ToSchema)]
#[schema(example = json!({"id": "room_abc", "name": "Movie Night", "created_by": "user123", "status": "active", "member_count": 5, "created_at": 1700000000}))]
pub struct RoomSchema {
    pub id: String,
    pub name: String,
    pub created_by: String,
    pub status: String,
    pub member_count: i32,
    pub created_at: i64,
}

#[derive(ToSchema)]
#[schema(example = json!({"id": "media_abc", "room_id": "room_abc", "url": "https://example.com/video.mp4", "provider": "direct", "title": "video.mp4", "position": 0, "added_at": 1700000000, "added_by": "user123"}))]
pub struct MediaSchema {
    pub id: String,
    pub room_id: String,
    pub url: String,
    pub provider: String,
    pub title: String,
    pub position: i32,
    pub added_at: i64,
    pub added_by: String,
}

#[derive(ToSchema)]
#[schema(example = json!({"room_id": "room_abc", "playing_media_id": "media_abc", "position": 42.5, "speed": 1.0, "is_playing": true, "updated_at": 1700000000, "version": 1}))]
pub struct PlaybackStateSchema {
    pub room_id: String,
    pub playing_media_id: String,
    pub position: f64,
    pub speed: f64,
    pub is_playing: bool,
    pub updated_at: i64,
    pub version: i32,
}

#[derive(ToSchema)]
#[schema(example = json!({"room_id": "room_abc", "user_id": "user123", "username": "alice", "permissions": 7, "joined_at": 1700000000, "is_online": true}))]
pub struct RoomMemberSchema {
    pub room_id: String,
    pub user_id: String,
    pub username: String,
    pub permissions: i64,
    pub joined_at: i64,
    pub is_online: bool,
}

// --- Auth schemas ---

#[derive(ToSchema)]
#[schema(example = json!({"username": "alice", "password": "secret123", "email": "alice@example.com"}))]
pub struct RegisterRequestSchema {
    pub username: String,
    pub password: String,
    pub email: String,
}

#[derive(ToSchema)]
pub struct RegisterResponseSchema {
    pub user: Option<UserSchema>,
    pub access_token: String,
    pub refresh_token: String,
}

#[derive(ToSchema)]
#[schema(example = json!({"username": "alice", "password": "secret123"}))]
pub struct LoginRequestSchema {
    pub username: String,
    pub password: String,
}

#[derive(ToSchema)]
pub struct LoginResponseSchema {
    pub user: Option<UserSchema>,
    pub access_token: String,
    pub refresh_token: String,
}

#[derive(ToSchema)]
#[schema(example = json!({"refresh_token": "eyJ..."}))]
pub struct RefreshTokenRequestSchema {
    pub refresh_token: String,
}

#[derive(ToSchema)]
pub struct RefreshTokenResponseSchema {
    pub access_token: String,
    pub refresh_token: String,
}

// --- Room schemas ---

#[derive(ToSchema)]
#[schema(example = json!({"name": "Movie Night", "password": ""}))]
pub struct CreateRoomRequestSchema {
    pub name: String,
    #[schema(default = "")]
    pub password: String,
}

#[derive(ToSchema)]
pub struct CreateRoomResponseSchema {
    pub room: Option<RoomSchema>,
}

#[derive(ToSchema)]
pub struct GetRoomResponseSchema {
    pub room: Option<RoomSchema>,
    pub playback_state: Option<PlaybackStateSchema>,
}

#[derive(ToSchema)]
#[schema(example = json!({"password": ""}))]
pub struct JoinRoomRequestSchema {
    #[schema(default = "")]
    pub password: String,
}

#[derive(ToSchema)]
pub struct JoinRoomResponseSchema {
    pub room: Option<RoomSchema>,
    pub playback_state: Option<PlaybackStateSchema>,
    pub members: Vec<RoomMemberSchema>,
}

#[derive(ToSchema)]
pub struct LeaveRoomResponseSchema {
    pub success: bool,
}

#[derive(ToSchema)]
pub struct DeleteRoomResponseSchema {
    pub success: bool,
}

#[derive(ToSchema)]
pub struct ListRoomsResponseSchema {
    pub rooms: Vec<RoomSchema>,
    pub total: i32,
}

#[derive(ToSchema)]
pub struct GetRoomMembersResponseSchema {
    pub members: Vec<RoomMemberSchema>,
}

#[derive(ToSchema)]
pub struct CheckRoomResponseSchema {
    pub exists: bool,
    pub requires_password: bool,
    pub name: String,
}

// --- Media schemas ---

#[derive(ToSchema)]
#[schema(example = json!({"url": "https://example.com/video.mp4", "provider": "", "title": "My Video"}))]
pub struct AddMediaRequestSchema {
    pub url: String,
    #[schema(default = "")]
    pub provider: String,
    pub title: String,
}

#[derive(ToSchema)]
pub struct AddMediaResponseSchema {
    pub media: Option<MediaSchema>,
}

#[derive(ToSchema)]
pub struct ListPlaylistResponseSchema {
    pub media: Vec<MediaSchema>,
    pub total: i32,
}

// --- Playback schemas ---

#[derive(ToSchema)]
#[schema(example = json!({"position": 42.5}))]
pub struct SeekRequestSchema {
    pub position: f64,
}

#[derive(ToSchema)]
#[schema(example = json!({"speed": 1.5}))]
pub struct ChangeSpeedRequestSchema {
    pub speed: f64,
}

#[derive(ToSchema)]
#[schema(example = json!({"media_id": "media_abc"}))]
pub struct SwitchMediaRequestSchema {
    pub media_id: String,
}

#[derive(ToSchema)]
pub struct GetPlaybackStateResponseSchema {
    pub playback_state: Option<PlaybackStateSchema>,
}

// --- User schemas ---

#[derive(ToSchema)]
pub struct GetProfileResponseSchema {
    pub user: Option<UserSchema>,
}

#[derive(ToSchema)]
#[schema(example = json!({"new_username": "bob"}))]
pub struct SetUsernameRequestSchema {
    pub new_username: String,
}

#[derive(ToSchema)]
pub struct SetUsernameResponseSchema {
    pub success: bool,
}

#[derive(ToSchema)]
#[schema(example = json!({"new_password": "newsecret123"}))]
pub struct SetPasswordRequestSchema {
    pub new_password: String,
}

#[derive(ToSchema)]
pub struct SetPasswordResponseSchema {
    pub success: bool,
}

// --- WebRTC schemas ---

#[derive(ToSchema)]
pub struct IceServerSchema {
    pub urls: Vec<String>,
    pub username: Option<String>,
    pub credential: Option<String>,
}

#[derive(ToSchema)]
pub struct GetIceServersResponseSchema {
    pub servers: Vec<IceServerSchema>,
}

// --- Chat schemas ---

#[derive(ToSchema)]
#[schema(example = json!({"content": "Hello everyone!"}))]
pub struct SendMessageRequestSchema {
    pub content: String,
}

#[derive(ToSchema)]
pub struct SendMessageResponseSchema {
    pub id: String,
    pub room_id: String,
    pub user_id: String,
    pub username: String,
    pub content: String,
    pub created_at: String,
}

#[derive(ToSchema)]
pub struct ChatHistoryResponseSchema {
    pub messages: Vec<ChatMessageSchema>,
}

#[derive(ToSchema)]
pub struct ChatMessageSchema {
    pub id: String,
    pub room_id: String,
    pub user_id: String,
    pub username: String,
    pub content: String,
    pub created_at: String,
}

// --- Health / Public schemas ---

#[derive(ToSchema)]
pub struct PublicSettingsSchema {
    pub signup_enabled: bool,
    pub allow_room_creation: bool,
    pub max_rooms_per_user: i64,
    pub max_members_per_room: i64,
}

#[derive(ToSchema)]
pub struct ErrorResponseSchema {
    pub error: String,
    pub status: u16,
}

// ============== Security modifier ==============

struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        if let Some(components) = openapi.components.as_mut() {
            components.add_security_scheme(
                "bearer_auth",
                SecurityScheme::Http(
                    HttpBuilder::new()
                        .scheme(HttpAuthScheme::Bearer)
                        .bearer_format("JWT")
                        .build(),
                ),
            );
        }
    }
}

// ============== OpenAPI doc ==============

#[derive(OpenApi)]
#[openapi(
    info(
        title = "SyncTV API",
        version = "0.1.0",
        description = "SyncTV - Real-time synchronized video watching platform.\n\nThis API provides endpoints for authentication, room management, media/playlist control, playback synchronization, chat, and WebRTC configuration.",
        license(name = "MIT OR Apache-2.0"),
    ),
    paths(
        // Health
        path_health,
        path_metrics,
        // Auth
        path_register,
        path_login,
        path_refresh_token,
        // User
        path_get_me,
        path_logout,
        path_update_username,
        path_update_password,
        path_get_joined_rooms,
        // Room discovery
        path_check_room,
        path_list_rooms,
        path_hot_rooms,
        // Room management
        path_create_room,
        path_get_room,
        path_join_room,
        path_leave_room,
        path_delete_room,
        path_get_room_members,
        path_get_room_settings,
        // Media
        path_add_media,
        path_remove_media,
        path_get_playlist,
        // Playback
        path_play,
        path_pause,
        path_seek,
        path_change_speed,
        path_switch_media,
        path_get_playback_state,
        // Chat
        path_send_chat,
        path_get_chat_history,
        // WebRTC
        path_get_ice_servers,
        // Public
        path_public_settings,
    ),
    components(schemas(
        UserSchema,
        RoomSchema,
        MediaSchema,
        PlaybackStateSchema,
        RoomMemberSchema,
        RegisterRequestSchema,
        RegisterResponseSchema,
        LoginRequestSchema,
        LoginResponseSchema,
        RefreshTokenRequestSchema,
        RefreshTokenResponseSchema,
        CreateRoomRequestSchema,
        CreateRoomResponseSchema,
        GetRoomResponseSchema,
        JoinRoomRequestSchema,
        JoinRoomResponseSchema,
        LeaveRoomResponseSchema,
        DeleteRoomResponseSchema,
        ListRoomsResponseSchema,
        GetRoomMembersResponseSchema,
        CheckRoomResponseSchema,
        AddMediaRequestSchema,
        AddMediaResponseSchema,
        ListPlaylistResponseSchema,
        SeekRequestSchema,
        ChangeSpeedRequestSchema,
        SwitchMediaRequestSchema,
        GetPlaybackStateResponseSchema,
        GetProfileResponseSchema,
        SetUsernameRequestSchema,
        SetUsernameResponseSchema,
        SetPasswordRequestSchema,
        SetPasswordResponseSchema,
        IceServerSchema,
        GetIceServersResponseSchema,
        SendMessageRequestSchema,
        SendMessageResponseSchema,
        ChatHistoryResponseSchema,
        ChatMessageSchema,
        PublicSettingsSchema,
        ErrorResponseSchema,
    )),
    modifiers(&SecurityAddon),
    tags(
        (name = "health", description = "Health check and monitoring"),
        (name = "auth", description = "Authentication (register, login, token refresh)"),
        (name = "user", description = "User profile and account management"),
        (name = "rooms", description = "Room discovery and management"),
        (name = "media", description = "Media/playlist management"),
        (name = "playback", description = "Playback synchronization control"),
        (name = "chat", description = "Chat and danmaku messaging"),
        (name = "webrtc", description = "WebRTC configuration"),
        (name = "public", description = "Public endpoints (no auth required)"),
    )
)]
pub struct ApiDoc;

// ============== Path definitions ==============

#[utoipa::path(
    get,
    path = "/health",
    tag = "health",
    responses((status = 200, description = "Server is healthy", body = String))
)]
pub async fn path_health() {}

#[utoipa::path(
    get,
    path = "/metrics",
    tag = "health",
    responses((status = 200, description = "Prometheus metrics", content_type = "text/plain"))
)]
pub async fn path_metrics() {}

// --- Auth paths ---

#[utoipa::path(
    post,
    path = "/api/auth/register",
    tag = "auth",
    request_body = RegisterRequestSchema,
    responses(
        (status = 200, description = "Registration successful", body = RegisterResponseSchema),
        (status = 400, description = "Bad request", body = ErrorResponseSchema),
    )
)]
pub async fn path_register() {}

#[utoipa::path(
    post,
    path = "/api/auth/login",
    tag = "auth",
    request_body = LoginRequestSchema,
    responses(
        (status = 200, description = "Login successful", body = LoginResponseSchema),
        (status = 401, description = "Invalid credentials", body = ErrorResponseSchema),
    )
)]
pub async fn path_login() {}

#[utoipa::path(
    post,
    path = "/api/auth/refresh",
    tag = "auth",
    request_body = RefreshTokenRequestSchema,
    responses(
        (status = 200, description = "Token refreshed", body = RefreshTokenResponseSchema),
        (status = 401, description = "Invalid refresh token", body = ErrorResponseSchema),
    )
)]
pub async fn path_refresh_token() {}

// --- User paths ---

#[utoipa::path(
    get,
    path = "/api/user/me",
    tag = "user",
    security(("bearer_auth" = [])),
    responses(
        (status = 200, description = "Current user profile", body = GetProfileResponseSchema),
        (status = 401, description = "Unauthorized", body = ErrorResponseSchema),
    )
)]
pub async fn path_get_me() {}

#[utoipa::path(
    post,
    path = "/api/user/logout",
    tag = "user",
    security(("bearer_auth" = [])),
    responses(
        (status = 200, description = "Logout successful"),
    )
)]
pub async fn path_logout() {}

#[utoipa::path(
    post,
    path = "/api/user/username",
    tag = "user",
    security(("bearer_auth" = [])),
    request_body = SetUsernameRequestSchema,
    responses(
        (status = 200, description = "Username updated", body = SetUsernameResponseSchema),
        (status = 400, description = "Bad request", body = ErrorResponseSchema),
    )
)]
pub async fn path_update_username() {}

#[utoipa::path(
    post,
    path = "/api/user/password",
    tag = "user",
    security(("bearer_auth" = [])),
    request_body = SetPasswordRequestSchema,
    responses(
        (status = 200, description = "Password updated", body = SetPasswordResponseSchema),
        (status = 400, description = "Bad request", body = ErrorResponseSchema),
    )
)]
pub async fn path_update_password() {}

#[utoipa::path(
    get,
    path = "/api/user/rooms",
    tag = "user",
    security(("bearer_auth" = [])),
    responses(
        (status = 200, description = "List of joined rooms", body = ListRoomsResponseSchema),
    )
)]
pub async fn path_get_joined_rooms() {}

// --- Room discovery paths ---

#[utoipa::path(
    get,
    path = "/api/room/check/{room_id}",
    tag = "rooms",
    params(("room_id" = String, Path, description = "Room ID")),
    responses(
        (status = 200, description = "Room check result", body = CheckRoomResponseSchema),
    )
)]
pub async fn path_check_room() {}

#[utoipa::path(
    get,
    path = "/api/room/list",
    tag = "rooms",
    responses(
        (status = 200, description = "List of rooms", body = ListRoomsResponseSchema),
    )
)]
pub async fn path_list_rooms() {}

#[utoipa::path(
    get,
    path = "/api/room/hot",
    tag = "rooms",
    responses(
        (status = 200, description = "Hot rooms sorted by activity", body = ListRoomsResponseSchema),
    )
)]
pub async fn path_hot_rooms() {}

// --- Room management paths ---

#[utoipa::path(
    post,
    path = "/api/rooms",
    tag = "rooms",
    security(("bearer_auth" = [])),
    request_body = CreateRoomRequestSchema,
    responses(
        (status = 200, description = "Room created", body = CreateRoomResponseSchema),
        (status = 400, description = "Bad request", body = ErrorResponseSchema),
    )
)]
pub async fn path_create_room() {}

#[utoipa::path(
    get,
    path = "/api/rooms/{room_id}",
    tag = "rooms",
    security(("bearer_auth" = [])),
    params(("room_id" = String, Path, description = "Room ID")),
    responses(
        (status = 200, description = "Room details", body = GetRoomResponseSchema),
        (status = 404, description = "Room not found", body = ErrorResponseSchema),
    )
)]
pub async fn path_get_room() {}

#[utoipa::path(
    post,
    path = "/api/rooms/{room_id}/join",
    tag = "rooms",
    security(("bearer_auth" = [])),
    params(("room_id" = String, Path, description = "Room ID")),
    request_body = JoinRoomRequestSchema,
    responses(
        (status = 200, description = "Joined room", body = JoinRoomResponseSchema),
        (status = 404, description = "Room not found", body = ErrorResponseSchema),
    )
)]
pub async fn path_join_room() {}

#[utoipa::path(
    post,
    path = "/api/rooms/{room_id}/leave",
    tag = "rooms",
    security(("bearer_auth" = [])),
    params(("room_id" = String, Path, description = "Room ID")),
    responses(
        (status = 200, description = "Left room", body = LeaveRoomResponseSchema),
    )
)]
pub async fn path_leave_room() {}

#[utoipa::path(
    delete,
    path = "/api/rooms/{room_id}",
    tag = "rooms",
    security(("bearer_auth" = [])),
    params(("room_id" = String, Path, description = "Room ID")),
    responses(
        (status = 200, description = "Room deleted", body = DeleteRoomResponseSchema),
        (status = 403, description = "Forbidden", body = ErrorResponseSchema),
    )
)]
pub async fn path_delete_room() {}

#[utoipa::path(
    get,
    path = "/api/rooms/{room_id}/members",
    tag = "rooms",
    security(("bearer_auth" = [])),
    params(("room_id" = String, Path, description = "Room ID")),
    responses(
        (status = 200, description = "Room members", body = GetRoomMembersResponseSchema),
    )
)]
pub async fn path_get_room_members() {}

#[utoipa::path(
    get,
    path = "/api/rooms/{room_id}/settings",
    tag = "rooms",
    params(("room_id" = String, Path, description = "Room ID")),
    responses(
        (status = 200, description = "Room settings"),
    )
)]
pub async fn path_get_room_settings() {}

// --- Media paths ---

#[utoipa::path(
    post,
    path = "/api/rooms/{room_id}/media",
    tag = "media",
    security(("bearer_auth" = [])),
    params(("room_id" = String, Path, description = "Room ID")),
    request_body = AddMediaRequestSchema,
    responses(
        (status = 200, description = "Media added", body = AddMediaResponseSchema),
        (status = 400, description = "Bad request", body = ErrorResponseSchema),
    )
)]
pub async fn path_add_media() {}

#[utoipa::path(
    delete,
    path = "/api/rooms/{room_id}/media/{media_id}",
    tag = "media",
    security(("bearer_auth" = [])),
    params(
        ("room_id" = String, Path, description = "Room ID"),
        ("media_id" = String, Path, description = "Media ID"),
    ),
    responses(
        (status = 200, description = "Media removed"),
        (status = 404, description = "Media not found", body = ErrorResponseSchema),
    )
)]
pub async fn path_remove_media() {}

#[utoipa::path(
    get,
    path = "/api/rooms/{room_id}/media",
    tag = "media",
    security(("bearer_auth" = [])),
    params(("room_id" = String, Path, description = "Room ID")),
    responses(
        (status = 200, description = "Playlist contents", body = ListPlaylistResponseSchema),
    )
)]
pub async fn path_get_playlist() {}

// --- Playback paths ---

#[utoipa::path(
    post,
    path = "/api/rooms/{room_id}/playback/play",
    tag = "playback",
    security(("bearer_auth" = [])),
    params(("room_id" = String, Path, description = "Room ID")),
    responses((status = 200, description = "Playback resumed"))
)]
pub async fn path_play() {}

#[utoipa::path(
    post,
    path = "/api/rooms/{room_id}/playback/pause",
    tag = "playback",
    security(("bearer_auth" = [])),
    params(("room_id" = String, Path, description = "Room ID")),
    responses((status = 200, description = "Playback paused"))
)]
pub async fn path_pause() {}

#[utoipa::path(
    post,
    path = "/api/rooms/{room_id}/playback/seek",
    tag = "playback",
    security(("bearer_auth" = [])),
    params(("room_id" = String, Path, description = "Room ID")),
    request_body = SeekRequestSchema,
    responses((status = 200, description = "Seeked to position"))
)]
pub async fn path_seek() {}

#[utoipa::path(
    post,
    path = "/api/rooms/{room_id}/playback/speed",
    tag = "playback",
    security(("bearer_auth" = [])),
    params(("room_id" = String, Path, description = "Room ID")),
    request_body = ChangeSpeedRequestSchema,
    responses((status = 200, description = "Speed changed"))
)]
pub async fn path_change_speed() {}

#[utoipa::path(
    post,
    path = "/api/rooms/{room_id}/playback/switch",
    tag = "playback",
    security(("bearer_auth" = [])),
    params(("room_id" = String, Path, description = "Room ID")),
    request_body = SwitchMediaRequestSchema,
    responses((status = 200, description = "Switched to media"))
)]
pub async fn path_switch_media() {}

#[utoipa::path(
    get,
    path = "/api/rooms/{room_id}/playback",
    tag = "playback",
    security(("bearer_auth" = [])),
    params(("room_id" = String, Path, description = "Room ID")),
    responses(
        (status = 200, description = "Current playback state", body = GetPlaybackStateResponseSchema),
    )
)]
pub async fn path_get_playback_state() {}

// --- Chat paths ---

#[utoipa::path(
    post,
    path = "/api/rooms/{room_id}/chat",
    tag = "chat",
    security(("bearer_auth" = [])),
    params(("room_id" = String, Path, description = "Room ID")),
    request_body = SendMessageRequestSchema,
    responses(
        (status = 200, description = "Message sent", body = SendMessageResponseSchema),
    )
)]
pub async fn path_send_chat() {}

#[utoipa::path(
    get,
    path = "/api/rooms/{room_id}/chat",
    tag = "chat",
    security(("bearer_auth" = [])),
    params(
        ("room_id" = String, Path, description = "Room ID"),
        ("before" = Option<String>, Query, description = "ISO 8601 datetime cursor for pagination"),
        ("limit" = Option<i32>, Query, description = "Max messages to return (default 50, max 100)"),
    ),
    responses(
        (status = 200, description = "Chat history", body = ChatHistoryResponseSchema),
    )
)]
pub async fn path_get_chat_history() {}

// --- WebRTC paths ---

#[utoipa::path(
    get,
    path = "/api/rooms/{room_id}/webrtc/ice-servers",
    tag = "webrtc",
    security(("bearer_auth" = [])),
    params(("room_id" = String, Path, description = "Room ID")),
    responses(
        (status = 200, description = "ICE server configuration", body = GetIceServersResponseSchema),
        (status = 403, description = "Not a room member", body = ErrorResponseSchema),
    )
)]
pub async fn path_get_ice_servers() {}

// --- Public paths ---

#[utoipa::path(
    get,
    path = "/api/public/settings",
    tag = "public",
    responses(
        (status = 200, description = "Public server settings", body = PublicSettingsSchema),
    )
)]
pub async fn path_public_settings() {}
