// This file is @generated by prost-build.
/// Publisher information
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PublisherInfo {
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
    /// Node hosting the publisher
    #[prost(string, tag = "2")]
    pub node_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub stream_key: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub metadata: ::core::option::Option<StreamMetadata>,
    #[prost(int64, tag = "5")]
    pub started_at: i64,
    #[prost(message, optional, tag = "6")]
    pub stats: ::core::option::Option<StreamStats>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamMetadata {
    /// h264, h265, etc.
    #[prost(string, tag = "1")]
    pub codec_video: ::prost::alloc::string::String,
    /// aac, opus, etc.
    #[prost(string, tag = "2")]
    pub codec_audio: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub width: i32,
    #[prost(int32, tag = "4")]
    pub height: i32,
    #[prost(int32, tag = "5")]
    pub fps: i32,
    #[prost(int32, tag = "6")]
    pub bitrate_video: i32,
    #[prost(int32, tag = "7")]
    pub bitrate_audio: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct StreamStats {
    #[prost(int64, tag = "1")]
    pub bytes_sent: i64,
    #[prost(int64, tag = "2")]
    pub bytes_received: i64,
    #[prost(int32, tag = "3")]
    pub viewer_count: i32,
    #[prost(double, tag = "4")]
    pub bitrate_kbps: f64,
    #[prost(int32, tag = "5")]
    pub frame_count: i32,
    #[prost(int32, tag = "6")]
    pub dropped_frames: i32,
    #[prost(double, tag = "7")]
    pub latency_ms: f64,
}
/// Get publisher
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPublisherRequest {
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetPublisherResponse {
    #[prost(message, optional, tag = "1")]
    pub publisher: ::core::option::Option<PublisherInfo>,
    #[prost(bool, tag = "2")]
    pub exists: bool,
}
/// Pull RTMP stream
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PullRtmpStreamRequest {
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub stream_key: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RtmpPacket {
    #[prost(enumeration = "rtmp_packet::PacketType", tag = "1")]
    pub r#type: i32,
    /// DTS (decode timestamp)
    #[prost(int64, tag = "2")]
    pub timestamp: i64,
    /// PTS (presentation timestamp)
    #[prost(int64, tag = "3")]
    pub pts: i64,
    #[prost(bytes = "vec", tag = "4")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag = "5")]
    pub is_keyframe: bool,
}
/// Nested message and enum types in `RtmpPacket`.
pub mod rtmp_packet {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum PacketType {
        Unknown = 0,
        Video = 1,
        Audio = 2,
        Metadata = 3,
        ScriptData = 4,
    }
    impl PacketType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unknown => "PACKET_TYPE_UNKNOWN",
                Self::Video => "PACKET_TYPE_VIDEO",
                Self::Audio => "PACKET_TYPE_AUDIO",
                Self::Metadata => "PACKET_TYPE_METADATA",
                Self::ScriptData => "PACKET_TYPE_SCRIPT_DATA",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "PACKET_TYPE_UNKNOWN" => Some(Self::Unknown),
                "PACKET_TYPE_VIDEO" => Some(Self::Video),
                "PACKET_TYPE_AUDIO" => Some(Self::Audio),
                "PACKET_TYPE_METADATA" => Some(Self::Metadata),
                "PACKET_TYPE_SCRIPT_DATA" => Some(Self::ScriptData),
                _ => None,
            }
        }
    }
}
/// Register publisher
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterPublisherRequest {
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub node_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub stream_key: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub metadata: ::core::option::Option<StreamMetadata>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterPublisherResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(message, optional, tag = "2")]
    pub publisher: ::core::option::Option<PublisherInfo>,
    /// Error message if registration failed
    #[prost(string, tag = "3")]
    pub error: ::prost::alloc::string::String,
}
/// Unregister publisher
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnregisterPublisherRequest {
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub node_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UnregisterPublisherResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
}
/// Get stream stats
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetStreamStatsRequest {
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetStreamStatsResponse {
    #[prost(message, optional, tag = "1")]
    pub stats: ::core::option::Option<StreamStats>,
    #[prost(bool, tag = "2")]
    pub exists: bool,
}
/// List active streams
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListStreamsRequest {
    /// Optional: filter by node
    #[prost(string, tag = "1")]
    pub node_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub page: i32,
    #[prost(int32, tag = "3")]
    pub page_size: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListStreamsResponse {
    #[prost(message, repeated, tag = "1")]
    pub streams: ::prost::alloc::vec::Vec<PublisherInfo>,
    #[prost(int32, tag = "2")]
    pub total: i32,
}
/// GOP cache messages (for fast start)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GopCacheRequest {
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GopCacheResponse {
    /// Last 2 GOPs
    #[prost(message, repeated, tag = "1")]
    pub packets: ::prost::alloc::vec::Vec<RtmpPacket>,
    #[prost(bool, tag = "2")]
    pub exists: bool,
}
/// Generated client implementations.
pub mod stream_relay_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Stream relay service for cross-node RTMP streaming
    #[derive(Debug, Clone)]
    pub struct StreamRelayServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl StreamRelayServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> StreamRelayServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> StreamRelayServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            StreamRelayServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Query which node has the publisher for a stream
        pub async fn get_publisher(
            &mut self,
            request: impl tonic::IntoRequest<super::GetPublisherRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetPublisherResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/synctv.stream.StreamRelayService/GetPublisher",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("synctv.stream.StreamRelayService", "GetPublisher"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Pull RTMP stream from publisher node (server streaming)
        pub async fn pull_rtmp_stream(
            &mut self,
            request: impl tonic::IntoRequest<super::PullRtmpStreamRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::RtmpPacket>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/synctv.stream.StreamRelayService/PullRtmpStream",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("synctv.stream.StreamRelayService", "PullRtmpStream"),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        /// Register as publisher for a stream
        pub async fn register_publisher(
            &mut self,
            request: impl tonic::IntoRequest<super::RegisterPublisherRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RegisterPublisherResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/synctv.stream.StreamRelayService/RegisterPublisher",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "synctv.stream.StreamRelayService",
                        "RegisterPublisher",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Unregister publisher
        pub async fn unregister_publisher(
            &mut self,
            request: impl tonic::IntoRequest<super::UnregisterPublisherRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UnregisterPublisherResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/synctv.stream.StreamRelayService/UnregisterPublisher",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "synctv.stream.StreamRelayService",
                        "UnregisterPublisher",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// Get stream statistics
        pub async fn get_stream_stats(
            &mut self,
            request: impl tonic::IntoRequest<super::GetStreamStatsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetStreamStatsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/synctv.stream.StreamRelayService/GetStreamStats",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("synctv.stream.StreamRelayService", "GetStreamStats"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// List active streams
        pub async fn list_streams(
            &mut self,
            request: impl tonic::IntoRequest<super::ListStreamsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListStreamsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/synctv.stream.StreamRelayService/ListStreams",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("synctv.stream.StreamRelayService", "ListStreams"),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod stream_relay_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with StreamRelayServiceServer.
    #[async_trait]
    pub trait StreamRelayService: std::marker::Send + std::marker::Sync + 'static {
        /// Query which node has the publisher for a stream
        async fn get_publisher(
            &self,
            request: tonic::Request<super::GetPublisherRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetPublisherResponse>,
            tonic::Status,
        >;
        /// Server streaming response type for the PullRtmpStream method.
        type PullRtmpStreamStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::RtmpPacket, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Pull RTMP stream from publisher node (server streaming)
        async fn pull_rtmp_stream(
            &self,
            request: tonic::Request<super::PullRtmpStreamRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::PullRtmpStreamStream>,
            tonic::Status,
        >;
        /// Register as publisher for a stream
        async fn register_publisher(
            &self,
            request: tonic::Request<super::RegisterPublisherRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RegisterPublisherResponse>,
            tonic::Status,
        >;
        /// Unregister publisher
        async fn unregister_publisher(
            &self,
            request: tonic::Request<super::UnregisterPublisherRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UnregisterPublisherResponse>,
            tonic::Status,
        >;
        /// Get stream statistics
        async fn get_stream_stats(
            &self,
            request: tonic::Request<super::GetStreamStatsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetStreamStatsResponse>,
            tonic::Status,
        >;
        /// List active streams
        async fn list_streams(
            &self,
            request: tonic::Request<super::ListStreamsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListStreamsResponse>,
            tonic::Status,
        >;
    }
    /// Stream relay service for cross-node RTMP streaming
    #[derive(Debug)]
    pub struct StreamRelayServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> StreamRelayServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for StreamRelayServiceServer<T>
    where
        T: StreamRelayService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/synctv.stream.StreamRelayService/GetPublisher" => {
                    #[allow(non_camel_case_types)]
                    struct GetPublisherSvc<T: StreamRelayService>(pub Arc<T>);
                    impl<
                        T: StreamRelayService,
                    > tonic::server::UnaryService<super::GetPublisherRequest>
                    for GetPublisherSvc<T> {
                        type Response = super::GetPublisherResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetPublisherRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StreamRelayService>::get_publisher(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetPublisherSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/synctv.stream.StreamRelayService/PullRtmpStream" => {
                    #[allow(non_camel_case_types)]
                    struct PullRtmpStreamSvc<T: StreamRelayService>(pub Arc<T>);
                    impl<
                        T: StreamRelayService,
                    > tonic::server::ServerStreamingService<super::PullRtmpStreamRequest>
                    for PullRtmpStreamSvc<T> {
                        type Response = super::RtmpPacket;
                        type ResponseStream = T::PullRtmpStreamStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PullRtmpStreamRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StreamRelayService>::pull_rtmp_stream(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PullRtmpStreamSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/synctv.stream.StreamRelayService/RegisterPublisher" => {
                    #[allow(non_camel_case_types)]
                    struct RegisterPublisherSvc<T: StreamRelayService>(pub Arc<T>);
                    impl<
                        T: StreamRelayService,
                    > tonic::server::UnaryService<super::RegisterPublisherRequest>
                    for RegisterPublisherSvc<T> {
                        type Response = super::RegisterPublisherResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RegisterPublisherRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StreamRelayService>::register_publisher(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RegisterPublisherSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/synctv.stream.StreamRelayService/UnregisterPublisher" => {
                    #[allow(non_camel_case_types)]
                    struct UnregisterPublisherSvc<T: StreamRelayService>(pub Arc<T>);
                    impl<
                        T: StreamRelayService,
                    > tonic::server::UnaryService<super::UnregisterPublisherRequest>
                    for UnregisterPublisherSvc<T> {
                        type Response = super::UnregisterPublisherResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UnregisterPublisherRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StreamRelayService>::unregister_publisher(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UnregisterPublisherSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/synctv.stream.StreamRelayService/GetStreamStats" => {
                    #[allow(non_camel_case_types)]
                    struct GetStreamStatsSvc<T: StreamRelayService>(pub Arc<T>);
                    impl<
                        T: StreamRelayService,
                    > tonic::server::UnaryService<super::GetStreamStatsRequest>
                    for GetStreamStatsSvc<T> {
                        type Response = super::GetStreamStatsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetStreamStatsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StreamRelayService>::get_stream_stats(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetStreamStatsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/synctv.stream.StreamRelayService/ListStreams" => {
                    #[allow(non_camel_case_types)]
                    struct ListStreamsSvc<T: StreamRelayService>(pub Arc<T>);
                    impl<
                        T: StreamRelayService,
                    > tonic::server::UnaryService<super::ListStreamsRequest>
                    for ListStreamsSvc<T> {
                        type Response = super::ListStreamsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListStreamsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as StreamRelayService>::list_streams(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListStreamsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for StreamRelayServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "synctv.stream.StreamRelayService";
    impl<T> tonic::server::NamedService for StreamRelayServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
