// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoginReq {
    #[prost(string, tag = "1")]
    pub host: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub password: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoginResp {
    #[prost(string, tag = "1")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub server_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MeReq {
    #[prost(string, tag = "1")]
    pub host: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MeResp {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub server_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetItemsReq {
    #[prost(string, tag = "1")]
    pub host: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub parent_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub search_term: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MediaStreamInfo {
    #[prost(string, tag = "1")]
    pub codec: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub language: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub display_title: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub display_language: ::prost::alloc::string::String,
    #[prost(bool, tag = "7")]
    pub is_default: bool,
    #[prost(uint64, tag = "8")]
    pub index: u64,
    #[prost(string, tag = "9")]
    pub protocol: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MediaSourceInfo {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub path: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub container: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub protocol: ::prost::alloc::string::String,
    #[prost(int64, tag = "6")]
    pub default_subtitle_stream_index: i64,
    #[prost(int64, tag = "7")]
    pub default_audio_stream_index: i64,
    #[prost(message, repeated, tag = "8")]
    pub media_stream_info: ::prost::alloc::vec::Vec<MediaStreamInfo>,
    #[prost(string, tag = "9")]
    pub direct_play_url: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub transcoding_url: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Item {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub parent_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub series_name: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub series_id: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub season_name: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub season_id: ::prost::alloc::string::String,
    #[prost(bool, tag = "9")]
    pub is_folder: bool,
    #[prost(message, repeated, tag = "10")]
    pub media_source_info: ::prost::alloc::vec::Vec<MediaSourceInfo>,
    #[prost(string, tag = "11")]
    pub collection_type: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetItemsResp {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<Item>,
    #[prost(uint64, tag = "2")]
    pub total_record_count: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetItemReq {
    #[prost(string, tag = "1")]
    pub host: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub item_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SystemInfoReq {
    #[prost(string, tag = "1")]
    pub host: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SystemInfoResp {
    #[prost(string, tag = "1")]
    pub system_update_level: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub operating_system_display_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub package_name: ::prost::alloc::string::String,
    #[prost(bool, tag = "4")]
    pub has_pending_restart: bool,
    #[prost(bool, tag = "5")]
    pub is_shutting_down: bool,
    #[prost(bool, tag = "6")]
    pub supports_library_monitor: bool,
    #[prost(int32, tag = "7")]
    pub web_socket_port_number: i32,
    #[prost(bool, tag = "8")]
    pub can_self_restart: bool,
    #[prost(bool, tag = "9")]
    pub can_self_update: bool,
    #[prost(bool, tag = "10")]
    pub can_launch_web_browser: bool,
    #[prost(string, tag = "11")]
    pub program_data_path: ::prost::alloc::string::String,
    #[prost(string, tag = "12")]
    pub items_by_name_path: ::prost::alloc::string::String,
    #[prost(string, tag = "13")]
    pub cache_path: ::prost::alloc::string::String,
    #[prost(string, tag = "14")]
    pub log_path: ::prost::alloc::string::String,
    #[prost(string, tag = "15")]
    pub internal_metadata_path: ::prost::alloc::string::String,
    #[prost(string, tag = "16")]
    pub transcoding_temp_path: ::prost::alloc::string::String,
    #[prost(int32, tag = "17")]
    pub http_server_port_number: i32,
    #[prost(bool, tag = "18")]
    pub supports_https: bool,
    #[prost(int32, tag = "19")]
    pub https_port_number: i32,
    #[prost(bool, tag = "20")]
    pub has_update_available: bool,
    #[prost(bool, tag = "21")]
    pub supports_auto_run_at_startup: bool,
    #[prost(bool, tag = "22")]
    pub hardware_acceleration_requires_premiere: bool,
    #[prost(string, tag = "23")]
    pub local_address: ::prost::alloc::string::String,
    #[prost(string, tag = "24")]
    pub wan_address: ::prost::alloc::string::String,
    #[prost(string, tag = "25")]
    pub server_name: ::prost::alloc::string::String,
    #[prost(string, tag = "26")]
    pub version: ::prost::alloc::string::String,
    #[prost(string, tag = "27")]
    pub operating_system: ::prost::alloc::string::String,
    #[prost(string, tag = "28")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FsListReq {
    #[prost(string, tag = "1")]
    pub host: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub path: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    pub start_index: u64,
    #[prost(uint64, tag = "5")]
    pub limit: u64,
    #[prost(string, tag = "6")]
    pub search_term: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Path {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FsListResp {
    #[prost(message, repeated, tag = "1")]
    pub paths: ::prost::alloc::vec::Vec<Path>,
    #[prost(message, repeated, tag = "2")]
    pub items: ::prost::alloc::vec::Vec<Item>,
    #[prost(uint64, tag = "3")]
    pub total: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogoutReq {
    #[prost(string, tag = "1")]
    pub host: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub token: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Empty {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlaybackInfoReq {
    #[prost(string, tag = "1")]
    pub host: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub item_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub media_source_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "6")]
    pub audio_stream_index: i32,
    #[prost(int32, tag = "7")]
    pub subtitle_stream_index: i32,
    #[prost(int64, tag = "8")]
    pub max_streaming_bitrate: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlaybackInfoResp {
    #[prost(string, tag = "1")]
    pub play_session_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub media_source_info: ::prost::alloc::vec::Vec<MediaSourceInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteActiveEncodingsReq {
    #[prost(string, tag = "1")]
    pub host: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub play_session_id: ::prost::alloc::string::String,
}
/// Generated server implementations.
pub mod emby_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with EmbyServer.
    #[async_trait]
    pub trait Emby: std::marker::Send + std::marker::Sync + 'static {
        async fn login(
            &self,
            request: tonic::Request<super::LoginReq>,
        ) -> std::result::Result<tonic::Response<super::LoginResp>, tonic::Status>;
        async fn me(
            &self,
            request: tonic::Request<super::MeReq>,
        ) -> std::result::Result<tonic::Response<super::MeResp>, tonic::Status>;
        async fn get_items(
            &self,
            request: tonic::Request<super::GetItemsReq>,
        ) -> std::result::Result<tonic::Response<super::GetItemsResp>, tonic::Status>;
        async fn get_item(
            &self,
            request: tonic::Request<super::GetItemReq>,
        ) -> std::result::Result<tonic::Response<super::Item>, tonic::Status>;
        async fn get_system_info(
            &self,
            request: tonic::Request<super::SystemInfoReq>,
        ) -> std::result::Result<tonic::Response<super::SystemInfoResp>, tonic::Status>;
        async fn fs_list(
            &self,
            request: tonic::Request<super::FsListReq>,
        ) -> std::result::Result<tonic::Response<super::FsListResp>, tonic::Status>;
        async fn logout(
            &self,
            request: tonic::Request<super::LogoutReq>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status>;
        async fn playback_info(
            &self,
            request: tonic::Request<super::PlaybackInfoReq>,
        ) -> std::result::Result<
            tonic::Response<super::PlaybackInfoResp>,
            tonic::Status,
        >;
        async fn delete_active_encodings(
            &self,
            request: tonic::Request<super::DeleteActiveEncodingsReq>,
        ) -> std::result::Result<tonic::Response<super::Empty>, tonic::Status>;
    }
    #[derive(Debug)]
    pub struct EmbyServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> EmbyServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for EmbyServer<T>
    where
        T: Emby,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/api.emby.Emby/Login" => {
                    #[allow(non_camel_case_types)]
                    struct LoginSvc<T: Emby>(pub Arc<T>);
                    impl<T: Emby> tonic::server::UnaryService<super::LoginReq>
                    for LoginSvc<T> {
                        type Response = super::LoginResp;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::LoginReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Emby>::login(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = LoginSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/api.emby.Emby/Me" => {
                    #[allow(non_camel_case_types)]
                    struct MeSvc<T: Emby>(pub Arc<T>);
                    impl<T: Emby> tonic::server::UnaryService<super::MeReq>
                    for MeSvc<T> {
                        type Response = super::MeResp;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::MeReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Emby>::me(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = MeSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/api.emby.Emby/GetItems" => {
                    #[allow(non_camel_case_types)]
                    struct GetItemsSvc<T: Emby>(pub Arc<T>);
                    impl<T: Emby> tonic::server::UnaryService<super::GetItemsReq>
                    for GetItemsSvc<T> {
                        type Response = super::GetItemsResp;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetItemsReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Emby>::get_items(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetItemsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/api.emby.Emby/GetItem" => {
                    #[allow(non_camel_case_types)]
                    struct GetItemSvc<T: Emby>(pub Arc<T>);
                    impl<T: Emby> tonic::server::UnaryService<super::GetItemReq>
                    for GetItemSvc<T> {
                        type Response = super::Item;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetItemReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Emby>::get_item(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetItemSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/api.emby.Emby/GetSystemInfo" => {
                    #[allow(non_camel_case_types)]
                    struct GetSystemInfoSvc<T: Emby>(pub Arc<T>);
                    impl<T: Emby> tonic::server::UnaryService<super::SystemInfoReq>
                    for GetSystemInfoSvc<T> {
                        type Response = super::SystemInfoResp;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::SystemInfoReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Emby>::get_system_info(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetSystemInfoSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/api.emby.Emby/FsList" => {
                    #[allow(non_camel_case_types)]
                    struct FsListSvc<T: Emby>(pub Arc<T>);
                    impl<T: Emby> tonic::server::UnaryService<super::FsListReq>
                    for FsListSvc<T> {
                        type Response = super::FsListResp;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::FsListReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Emby>::fs_list(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = FsListSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/api.emby.Emby/Logout" => {
                    #[allow(non_camel_case_types)]
                    struct LogoutSvc<T: Emby>(pub Arc<T>);
                    impl<T: Emby> tonic::server::UnaryService<super::LogoutReq>
                    for LogoutSvc<T> {
                        type Response = super::Empty;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::LogoutReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Emby>::logout(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = LogoutSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/api.emby.Emby/PlaybackInfo" => {
                    #[allow(non_camel_case_types)]
                    struct PlaybackInfoSvc<T: Emby>(pub Arc<T>);
                    impl<T: Emby> tonic::server::UnaryService<super::PlaybackInfoReq>
                    for PlaybackInfoSvc<T> {
                        type Response = super::PlaybackInfoResp;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PlaybackInfoReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Emby>::playback_info(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PlaybackInfoSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/api.emby.Emby/DeleteActiveEncodings" => {
                    #[allow(non_camel_case_types)]
                    struct DeleteActiveEncodingsSvc<T: Emby>(pub Arc<T>);
                    impl<
                        T: Emby,
                    > tonic::server::UnaryService<super::DeleteActiveEncodingsReq>
                    for DeleteActiveEncodingsSvc<T> {
                        type Response = super::Empty;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DeleteActiveEncodingsReq>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Emby>::delete_active_encodings(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DeleteActiveEncodingsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for EmbyServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "api.emby.Emby";
    impl<T> tonic::server::NamedService for EmbyServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
