// This file is @generated by prost-build.
/// Room member information (shared between admin and client APIs)
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RoomMember {
    #[prost(string, tag = "1")]
    pub room_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub username: ::prost::alloc::string::String,
    #[prost(enumeration = "RoomMemberRole", tag = "4")]
    pub role: i32,
    /// Effective permissions (calculated from role + added/removed)
    #[prost(uint64, tag = "5")]
    pub permissions: u64,
    /// Allow/Deny permission pattern fields
    /// For member role: uses added_permissions/removed_permissions
    /// For admin role: uses admin_added_permissions/admin_removed_permissions
    #[prost(uint64, tag = "6")]
    pub added_permissions: u64,
    #[prost(uint64, tag = "7")]
    pub removed_permissions: u64,
    #[prost(uint64, tag = "8")]
    pub admin_added_permissions: u64,
    #[prost(uint64, tag = "9")]
    pub admin_removed_permissions: u64,
    #[prost(int64, tag = "10")]
    pub joined_at: i64,
    #[prost(bool, tag = "11")]
    pub is_online: bool,
}
/// Global user role for RBAC
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum UserRole {
    Unspecified = 0,
    User = 1,
    Admin = 2,
    Root = 3,
}
impl UserRole {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "USER_ROLE_UNSPECIFIED",
            Self::User => "USER_ROLE_USER",
            Self::Admin => "USER_ROLE_ADMIN",
            Self::Root => "USER_ROLE_ROOT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "USER_ROLE_UNSPECIFIED" => Some(Self::Unspecified),
            "USER_ROLE_USER" => Some(Self::User),
            "USER_ROLE_ADMIN" => Some(Self::Admin),
            "USER_ROLE_ROOT" => Some(Self::Root),
            _ => None,
        }
    }
}
/// Account status
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum UserStatus {
    Unspecified = 0,
    Active = 1,
    Pending = 2,
    Banned = 3,
}
impl UserStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "USER_STATUS_UNSPECIFIED",
            Self::Active => "USER_STATUS_ACTIVE",
            Self::Pending => "USER_STATUS_PENDING",
            Self::Banned => "USER_STATUS_BANNED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "USER_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "USER_STATUS_ACTIVE" => Some(Self::Active),
            "USER_STATUS_PENDING" => Some(Self::Pending),
            "USER_STATUS_BANNED" => Some(Self::Banned),
            _ => None,
        }
    }
}
/// Room member role
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RoomMemberRole {
    Unspecified = 0,
    Guest = 1,
    Member = 2,
    Admin = 3,
    Creator = 4,
}
impl RoomMemberRole {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ROOM_MEMBER_ROLE_UNSPECIFIED",
            Self::Guest => "ROOM_MEMBER_ROLE_GUEST",
            Self::Member => "ROOM_MEMBER_ROLE_MEMBER",
            Self::Admin => "ROOM_MEMBER_ROLE_ADMIN",
            Self::Creator => "ROOM_MEMBER_ROLE_CREATOR",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ROOM_MEMBER_ROLE_UNSPECIFIED" => Some(Self::Unspecified),
            "ROOM_MEMBER_ROLE_GUEST" => Some(Self::Guest),
            "ROOM_MEMBER_ROLE_MEMBER" => Some(Self::Member),
            "ROOM_MEMBER_ROLE_ADMIN" => Some(Self::Admin),
            "ROOM_MEMBER_ROLE_CREATOR" => Some(Self::Creator),
            _ => None,
        }
    }
}
